drop table authors;
drop table votes;
drop table laws;

create table laws(
                     id number primary key,  -- nomer proektu zakona
                     title varchar(500),  -- nazva proektu
                     law_registation_id varchar(20),  -- rehyestracinyj nomer zakonu (my ne vykoryst.)
                     initiator varchar(100) -- xto iniciyuvav rozhlyad
);

create table authors(
                        law_id number references laws(id),  -- nomer proektu zakona
                        author varchar(50),  -- i'mya avtora
                        primary key (law_id, author)
);

create table votes(
                      law_id number references laws(id),  -- nomer proektu zakona
                      pearson varchar(50),  -- i'mya avtora
                      vote varchar(30),  -- rezul"tat holosuvannya
                      primary key (law_id, pearson)
);


insert into laws values (5067, 'Proekt Zakonu pro zapobihannya ta protydiyu lehalizaciyi (vidmyvannyu) doxodiv,  oderzhanyx zlochynnym shlyaxom,  finansuvannyu teroryzmu ta finansuvannyu rozpovsyudzhennya zbroyi masovoho znyshhennya', '1702-VII', 'Kabinet Ministriv Ukrayiny');
insert into laws values (5113, 'Proekt Zakonu pro zapobihannya korupciyi', '1700-VII', 'Kabinet Ministriv Ukrayiny');
insert into laws values (2763, 'Proekt Zakonu pro dostup do publichnoyi informaciyi', '2939-VI', 'Narodnyj deputat Ukrayiny');
insert into laws values (1187, 'Proekt Zakonu pro vyshhu osvitu', '1556-VII', 'Narodnyj deputat Ukrayiny');
insert into laws values (10155, 'Proekt Zakonu pro ekstrenu medychnu dopomohu', '5081-VI', 'Narodnyj deputat Ukrayiny');
insert into laws values (2273, 'Proekt Zakonu pro zaxyst personal"nyx danyx', '2297-VI', 'Narodnyj deputat Ukrayiny');

insert into authors values (5067, 'Yacenyuk A.P.');
insert into authors values (5113, 'Yacenyuk A.P.');
insert into authors values (2763, 'Shevchenko A.V.');
insert into authors values (10155, 'Baxteyeva T.D.');
insert into authors values (2273, 'Shevchuk O.B.');
insert into authors values (2273, 'Lytvyn V.M.');
insert into authors values (2273, 'Poloxalo V.I.');
insert into authors values (2273, 'Samojlyk K.S.');
insert into authors values (1187, 'Baloha V.I.');

insert into votes values(5067, 'Dunayev S.V.', 'Vidsutnij');
insert into votes values(5067, 'Yedin O.J.', 'Ne holosuvav');
insert into votes values(5067, 'Yeremeyev I.M.', 'Za');
insert into votes values(5067, 'Zhvaniya D.V.', 'Ne holosuvav');
insert into votes values(5067, 'Zherebnyuk V.M.', 'Vidsutnij');
insert into votes values(5067, 'Zhuravs"kyj V.S.', 'Ne holosuvav');
insert into votes values(5067, 'Zabolotnyj H.M.', 'Za');
insert into votes values(5067, 'Zarubins"kyj O.O.', 'Za');
insert into votes values(5067, 'Zvyahil"s"kyj Yu.L.', 'Za');
insert into votes values(5067, 'Zubyk V.V.', 'Vidsutnij');
insert into votes values(5067, 'Zubchevs"kyj O.P.', 'Vidsutnij');
insert into votes values(5067, 'Ivanyushhenko Yu.V.', 'Vidsutnij');
insert into votes values(5067, 'Ilyk R.R.', 'Za');
insert into votes values(5067, 'Il"yuk A.O.', 'Ne holosuvav');
insert into votes values(5067, 'Ionova M.M.', 'Za');
insert into votes values(5067, 'Ishhenko V.O.', 'Za');
insert into votes values(5067, 'Kaletnyk O.M.', 'Vidsutnya');
insert into votes values(5067, 'Kalyetnik I.H.', 'Vidsutnij');
insert into votes values(5067, 'Kal"chenko V.M.', 'Za');
insert into votes values(5067, 'Kanivec" O.L.', 'Za');
insert into votes values(5067, 'Karpuncov V.V.', 'Za');
insert into votes values(5067, 'Katerynchuk M.D.', 'Za');
insert into votes values(5067, 'Kacuba S.V.', 'Za');
insert into votes values(5067, 'Kyrylenko V.A.', 'Za');
insert into votes values(5067, 'Kyrylenko P.V.', 'Za');
insert into votes values(5067, 'Kilinkarov S.P.', 'Vidsutnij');
insert into votes values(5067, 'Kisse A.I.', 'Vidsutnij');
insert into votes values(5067, 'Klyuyev S.P.', 'Vidsutnij');
insert into votes values(5067, 'Knyazevych R.P.', 'Za');
insert into votes values(5067, 'Koval"chuk V.A.', 'Za');
insert into votes values(5067, 'Kozhem’yakin A.A.', 'Za');
insert into votes values(5067, 'Kolhanova O.V.', 'Ne holosuvala');
insert into votes values(5067, 'Kondratyuk O.K.', 'Za');
insert into votes values(5067, 'Korzhev A.L.', 'Vidsutnij');
insert into votes values(5067, 'Korolyuk V.A.', 'Za');
insert into votes values(5067, 'Koshulyns"kyj R.V.', 'Za');
insert into votes values(5067, 'Kryvec"kyj I.I.', 'Za');
insert into votes values(5067, 'Kruk Yu.B.', 'Ne holosuvav');
insert into votes values(5067, 'Kudrya V.I.', 'Vidsutnij');
insert into votes values(5067, 'Kuz"menko S.A.', 'Za');
insert into votes values(5067, 'Kulinich O.I.', 'Vidsutnij');
insert into votes values(5067, 'Kunchenko O.P.', 'Vidsutnij');
insert into votes values(5067, 'Kupchak V.R.', 'Za');
insert into votes values(5067, 'Kurovs"kyj I.I.', 'Ne holosuvav*');
insert into votes values(5067, 'Kutovyj V.H.', 'Za');
insert into votes values(5067, 'Kucheruk M.H.', 'Ne holosuvav');
insert into votes values(5067, 'Labuns"ka A.V.', 'Za');
insert into votes values(5067, 'Lan"o M.I.', 'Za');
insert into votes values(5067, 'Levchenko O.V.', 'Vidsutnya');
insert into votes values(5067, 'Lelyuk O.V.', 'Vidsutnij');
insert into votes values(5067, 'Lytvyn V.M.', 'Za');
insert into votes values(5067, 'Lopachak M.R.', 'Za');
insert into votes values(5067, 'Luk’yanov V.V.', 'Vidsutnij');
insert into votes values(5067, 'Lunchenko V.V.', 'Za');
insert into votes values(5067, 'L"ovochkina Yu.V.', 'Vidsutnya');
insert into votes values(5067, 'Lyutikova V.I.', 'Vidsutnya');
insert into votes values(5067, 'Lyashko O.V.', 'Za');
insert into votes values(5067, 'Makul L.Ya.', 'Za');
insert into votes values(5067, 'Mal"cev V.O.', 'Vidsutnij');
insert into votes values(5067, 'Martynenko M.V.', 'Za');
insert into votes values(5067, 'Martynyuk L.S.', 'Za');
insert into votes values(5067, 'Martovyc"kyj A.V.', 'Vidsutnij');
insert into votes values(5067, 'Matvyeyev V.H.', 'Vidsutnij');
insert into votes values(5067, 'Matios M.V.', 'Ne holosuvala');
insert into votes values(5067, 'Medyanyk V.Yu.', 'Vidsutnij');
insert into votes values(5067, 'Mel"nyk S.A.', 'Ne holosuvav');
insert into votes values(5067, 'Mel"nychuk L.Yu.', 'Za');
insert into votes values(5067, 'Myryms"kyj L.Yu.', 'Ne holosuvav');
insert into votes values(5067, 'Myrnyj O.B.', 'Za');
insert into votes values(5067, 'Mysyk V.Yu.', 'Vidsutnij');
insert into votes values(5067, 'Myxal"chyshyn Yu.A.', 'Za');
insert into votes values(5067, 'Miroshnychenko Yu.R.', 'Vidsutnij');
insert into votes values(5067, 'Mishhenko S.H.', 'Za');
insert into votes values(5067, 'Momot O.I.', 'Ne holosuvav');
insert into votes values(5067, 'Moskalenko Ya.M.', 'Za');
insert into votes values(5067, 'Mochkov O.B.', 'Za');
insert into votes values(5067, 'Moshens"kyj V.Z.', 'Za');
insert into votes values(5067, 'Mxitaryan N.M.', 'Vidsutnij');
insert into votes values(5067, 'Nehoj F.F.', 'Za');
insert into votes values(5067, 'Nemilostivyj V.O.', 'Za');
insert into votes values(5067, 'Nechayev O.I.', 'Vidsutnij');
insert into votes values(5067, 'Novak N.V.', 'Za');
insert into votes values(5067, 'Odarchenko Yu.V.', 'Za');
insert into votes values(5067, 'Omel"chenko V.P.', 'Vidsutnij');
insert into votes values(5067, 'Onyshhenko O.R.', 'Vidsutnij');
insert into votes values(5067, 'Orobec" L.Yu.', 'Vidsutnya');
insert into votes values(5067, 'Ostapchuk V.M.', 'Ne holosuvav');
insert into votes values(5067, 'Pavelko A.V.', 'Za');
insert into votes values(5067, 'Pavlov K.Yu.', 'Vidsutnij');
insert into votes values(5067, 'Pazynyak V.S.', 'Za');
insert into votes values(5067, 'Palatnyj A.L.', 'Ne holosuvav');
insert into votes values(5067, 'Pan"kevych O.I.', 'Za');
insert into votes values(5067, 'Parubok O.N.', 'Vidsutnij');
insert into votes values(5067, 'Pashyns"kyj S.V.', 'Ne holosuvav');
insert into votes values(5067, 'Pexov V.A.', 'Ne holosuvav');
insert into votes values(5067, 'Pylypyshyn V.P.', 'Za');
insert into votes values(5067, 'Pysarenko V.V.', 'Vidsutnij');
insert into votes values(5067, 'Pinchuk A.P.', 'Za');
insert into votes values(5067, 'Povalij T.M.', 'Vidsutnya');
insert into votes values(5067, 'Polyakov V.L.', 'Za');
insert into votes values(5067, 'Ponomar"ov A.V.', 'Vidsutnij');
insert into votes values(5067, 'Popesku I.V.', 'Za');
insert into votes values(5067, 'Presman O.S.', 'Ne holosuvav');
insert into votes values(5067, 'Prysyazhnyuk O.A.', 'Vidsutnij');
insert into votes values(5067, 'Prodyvus V.S.', 'Za');
insert into votes values(5067, 'Pshonka A.V.', 'Vidsutnij');
insert into votes values(5067, 'Raupov R.B.', 'Za');
insert into votes values(5067, 'Rybak V.V.', 'Vidsutnij');
insert into votes values(5067, 'Ryzhenkov O.M.', 'Vidsutnij');
insert into votes values(5067, 'Rozenko P.V.', 'Za');
insert into votes values(5067, 'Rud"kovs"kyj M.M.', 'Za');
insert into votes values(5067, 'Sabij I.M.', 'Za');
insert into votes values(5067, 'Sal"do V.V.', 'Ne holosuvav');
insert into votes values(5067, 'Samojlenko Yu.P.', 'Vidsutnij');
insert into votes values(5067, 'Selivarov A.B.', 'Vidsutnij');
insert into votes values(5067, 'Senchenko A.V.', 'Za');
insert into votes values(5067, 'Sex I.I.', 'Za');
insert into votes values(5067, 'Syrotyuk Yu.M.', 'Za');
insert into votes values(5067, 'Sikora O.M.', 'Za');
insert into votes values(5067, 'Skosar I.Ye.', 'Vidsutnij');
insert into votes values(5067, 'Smityux H.Ye.', 'Ne holosuvav');
insert into votes values(5067, 'Soloshenko M.P.', 'Vidsutnij');
insert into votes values(5067, 'Soroka M.P.', 'Za');
insert into votes values(5067, 'Stadnijchuk R.V.', 'Vidsutnij');
insert into votes values(5067, 'Stojko I.M.', 'Za');
insert into votes values(5067, 'Struk V.O.', 'Vidsutnij');
insert into votes values(5067, 'Suxyj Ya.M.', 'Vidsutnij');
insert into votes values(5067, 'Tabalov A.O.', 'Ne holosuvav');
insert into votes values(5067, 'Tabachnik Ya.P.', 'Ne holosuvav');
insert into votes values(5067, 'Tedeyev E.S.', 'Vidsutnij');
insert into votes values(5067, 'Tymoshenko V.A.', 'Za');
insert into votes values(5067, 'Tihipko S.L.', 'Za');
insert into votes values(5067, 'Tomenko M.V.', 'Za');
insert into votes values(5067, 'Turmanov V.I.', 'Za');
insert into votes values(5067, 'Tyahnybok A.Ya.', 'Za');
insert into votes values(5067, 'Fabrykant S.S.', 'Za');
insert into votes values(5067, 'Farion I.D.', 'Za');
insert into votes values(5067, 'Fedorchuk Ya.P.', 'Za');
insert into votes values(5067, 'Fel"dman O.B.', 'Za');
insert into votes values(5067, 'Firsov Ye.P.', 'Za');
insert into votes values(5067, 'Fursin I.H.', 'Vidsutnij');
insert into votes values(5067, 'Xmel"nyc"kyj V.I.', 'Vidsutnij');
insert into votes values(5067, 'Xomutynnik V.Yu.', 'Ne holosuvav');
insert into votes values(5067, 'Cybenko P.S.', 'Vidsutnij');
insert into votes values(5067, 'Cherneha R.T.', 'Za');
insert into votes values(5067, 'Chechetov M.V.', 'Vidsutnij');
insert into votes values(5067, 'Chornovolenko O.V.', 'Za');
insert into votes values(5067, 'Chubatenko O.M.', 'Za');
insert into votes values(5067, 'Chudnovs"kyj V.O.', 'Za');
insert into votes values(5067, 'Shablatovych O.M.', 'Za');
insert into votes values(5067, 'Sharov I.F.', 'Za');
insert into votes values(5067, 'Shvec" V.D.', 'Za');
insert into votes values(5067, 'Shevchenko O.L.', 'Za');
insert into votes values(5067, 'Shevchuk O.B.', 'Za');
insert into votes values(5067, 'Shypko A.F.', 'Ne holosuvav');
insert into votes values(5067, 'Shkirya I.M.', 'Vidsutnij');
insert into votes values(5067, 'Shpenov D.Yu.', 'Vidsutnij');
insert into votes values(5067, 'Shul"ha V.P.', 'Za');
insert into votes values(5067, 'Shherban" A.V.', 'Za');
insert into votes values(5067, 'Yankiv I.T.', 'Za');
insert into votes values(5067, 'Yacenko A.V.', 'Ne holosuvav');
insert into votes values(5067, 'Ahafonova N.V.', 'Za');
insert into votes values(5067, 'Aleksyeyev I.V.', 'Vidsutnij');
insert into votes values(5067, 'Apostol M.V.', 'Za');
insert into votes values(5067, 'Arkallayev N.H.', 'Vidsutnij');
insert into votes values(5067, 'Bahrayev M.H.', 'Za');
insert into votes values(5067, 'Bajdyuk L.M.', 'Vidsutnya');
insert into votes values(5067, 'Balandin S.V.', 'Vidsutnij');
insert into votes values(5067, 'Baloha V.I.', 'Za');
insert into votes values(5067, 'Bandurov V.V.', 'Za');
insert into votes values(5067, 'Baxteyeva T.D.', 'Vidsutnya');
insert into votes values(5067, 'Benyuk B.M.', 'Za');
insert into votes values(5067, 'Berezkin S.S.', 'Za');
insert into votes values(5067, 'Bid"ovka V.A.', 'Vidsutnij');
insert into votes values(5067, 'Bilovol O.M.', 'Vidsutnij');
insert into votes values(5067, 'Blahodyr Yu.A.', 'Za');
insert into votes values(5067, 'Bobkov O.M.', 'Vidsutnij');
insert into votes values(5067, 'Bohdan R.D.', 'Za');
insert into votes values(5067, 'Bohuslayev V.O.', 'Vidsutnij');
insert into votes values(5067, 'Bojko V.S.', 'Vidsutnij');
insert into votes values(5067, 'Bondarenko O.A.', 'Vidsutnya');
insert into votes values(5067, 'Bondarchuk O.V.', 'Za');
insert into votes values(5067, 'Bort V.P.', 'Ne holosuvav');
insert into votes values(5067, 'Brajko S.B.', 'Vidsutnij');
insert into votes values(5067, 'Brychenko I.V.', 'Za');
insert into votes values(5067, 'Bulax V.V.', 'Vidsutnya');
insert into votes values(5067, 'Butkivs"kyj V.V.', 'Ne holosuvav');
insert into votes values(5067, 'Bushko I.I.', 'Za');
insert into votes values(5067, 'Vasyl"yev H.A.', 'Za');
insert into votes values(5067, 'Vasyunyk I.V.', 'Za');
insert into votes values(5067, 'Vecherko V.M.', 'Vidsutnij');
insert into votes values(5067, 'Vlasenko S.V.', 'Vidsutnij');
insert into votes values(5067, 'Volkov O.A.', 'Ne holosuvav');
insert into votes values(5067, 'Voropayev Yu.M.', 'Ne holosuvav');
insert into votes values(5067, 'Hanchukov O.K.', 'Vidsutnij');
insert into votes values(5067, 'Herashhenko I.V.', 'Za');
insert into votes values(5067, 'Herzhov Yu.I.', 'Za');
insert into votes values(5067, 'Hyellyer Ye.B.', 'Vidsutnij');
insert into votes values(5067, 'Hirshfel"d A.M.', 'Ne holosuvav');
insert into votes values(5067, 'Hlazunov S.M.', 'Vidsutnij');
insert into votes values(5067, 'Holovko M.J.', 'Za');
insert into votes values(5067, 'Honcharov A.D.', 'Vidsutnij');
insert into votes values(5067, 'Hordiyenko S.V.', 'Vidsutnij');
insert into votes values(5067, 'Horoxov S.O.', 'Vidsutnij');
insert into votes values(5067, 'Hrynevych L.M.', 'Za');
insert into votes values(5067, 'Hrycenko A.S.', 'Za');
insert into votes values(5067, 'Hrushevs"kyj V.A.', 'Ne holosuvav');
insert into votes values(5067, 'Huzenko K.O.', 'Vidsutnij');
insert into votes values(5067, 'Danilov V.B.', 'Za');
insert into votes values(5067, 'Dejch B.D.', 'Vidsutnij');
insert into votes values(5067, 'Demydko V.M.', 'Vidsutnij');
insert into votes values(5067, 'Demyanko M.I.', 'Vidsutnij');
insert into votes values(5067, 'Derevlyanyj V.T.', 'Za');
insert into votes values(5067, 'Derkach A.L.', 'Vidsutnij');
insert into votes values(5067, 'Dzhyha M.V.', 'Ne holosuvav');
insert into votes values(5067, 'Dzenzers"kyj D.V.', 'Za');
insert into votes values(5067, 'Dyriv A.B.', 'Za');
insert into votes values(5067, 'Dobkin D.M.', 'Vidsutnij');
insert into votes values(5067, 'Dombrovs"kyj O.H.', 'Za');
insert into votes values(5067, 'Donij O.S.', 'Za');
insert into votes values(5067, 'Dubil" V.O.', 'Za');
insert into votes values(5067, 'Dubovoj O.F.', 'Za');
insert into votes values(5067, 'Dudka O.I.', 'Za');
insert into votes values(5067, 'Yehorov O.M.', 'Vidsutnij');
insert into votes values(5067, 'Yemec" L.O.', 'Za');
insert into votes values(5067, 'Yefremov O.S.', 'Vidsutnij');
insert into votes values(5067, 'Zhevaho K.V.', 'Vidsutnij');
insert into votes values(5067, 'Zhuk M.V.', 'Ne holosuvav');
insert into votes values(5067, 'Zabzalyuk R.O.', 'Vidsutnij');
insert into votes values(5067, 'Zadorozhnyj V.K.', 'Vidsutnij');
insert into votes values(5067, 'Zac O.V.', 'Vidsutnij');
insert into votes values(5067, 'Zelyk R.B.', 'Za');
insert into votes values(5067, 'Zubko H.H.', 'Za');
insert into votes values(5067, 'Ivanchuk A.V.', 'Za');
insert into votes values(5067, 'Ivaxiv S.P.', 'Za');
insert into votes values(5067, 'Illyenko A.Yu.', 'Za');
insert into votes values(5067, 'Ilyashenko V.V.', 'Za');
insert into votes values(5067, 'Ioffe Yu.Ya.', 'Vidsutnij');
insert into votes values(5067, 'Kajda O.P.', 'Za');
insert into votes values(5067, 'Kaletnik H.M.', 'Vidsutnij');
insert into votes values(5067, 'Kal"cev S.F.', 'Za');
insert into votes values(5067, 'Kalyuzhnyj V.A.', 'Vidsutnij');
insert into votes values(5067, 'Kaplin S.M.', 'Za');
insert into votes values(5067, 'Kartashov Ye.H.', 'Ne holosuvav');
insert into votes values(5067, 'Kacuba V.M.', 'Za');
insert into votes values(5067, 'Kyj S.V.', 'Vidsutnij');
insert into votes values(5067, 'Kyrylenko I.H.', 'Za');
insert into votes values(5067, 'Kivalov S.V.', 'Za');
insert into votes values(5067, 'Kinax A.K.', 'Ne holosuvav');
insert into votes values(5067, 'Klimov L.M.', 'Ne holosuvav');
insert into votes values(5067, 'Knyazhyc"kyj M.L.', 'Za');
insert into votes values(5067, 'Koval" O.I.', 'Ne holosuvav');
insert into votes values(5067, 'Kovach V.I.', 'Za');
insert into votes values(5067, 'Kozub O.A.', 'Vidsutnij');
insert into votes values(5067, 'Kolesnikov B.V.', 'Vidsutnij');
insert into votes values(5067, 'Korzh P.P.', 'Ne holosuvav');
insert into votes values(5067, 'Kornijchuk O.O.', 'Za');
insert into votes values(5067, 'Kotelyak L.L.', 'Za');
insert into votes values(5067, 'Kravchuk V.P.', 'Vidsutnij');
insert into votes values(5067, 'Kruhlov M.P.', 'Ne holosuvav');
insert into votes values(5067, 'Krutij V.I.', 'Za');
insert into votes values(5067, 'Kuzhel" O.V.', 'Ne holosuvala*');
insert into votes values(5067, 'Kuz"muk O.I.', 'Ne holosuvav');
insert into votes values(5067, 'Kunicyn S.V.', 'Za');
insert into votes values(5067, 'Kuprejchyk I.V.', 'Za');
insert into votes values(5067, 'Kurennoj V.K.', 'Za');
insert into votes values(5067, 'Kurpil" S.V.', 'Za');
insert into votes values(5067, 'Kutovyj T.V.', 'Za');
insert into votes values(5067, 'Labazyuk S.P.', 'Za');
insert into votes values(5067, 'Landyk V.I.', 'Vidsutnij');
insert into votes values(5067, 'Levchenko M.O.', 'Vidsutnij');
insert into votes values(5067, 'Ledovs"kyx O.V.', 'Za');
insert into votes values(5067, 'Leonov E.V.', 'Za');
insert into votes values(5067, 'Lytvynov L.F.', 'Ne holosuvav');
insert into votes values(5067, 'Lukashuk O.H.', 'Za');
insert into votes values(5067, 'Luk’yanchuk R.V.', 'Za');
insert into votes values(5067, 'Lucenko I.S.', 'Za');
insert into votes values(5067, 'Lyubonenko Yu.V.', 'Vidsutnij');
insert into votes values(5067, 'Lyapina K.M.', 'Za');
insert into votes values(5067, 'Makeyenko V.V.', 'Za');
insert into votes values(5067, 'Malyshev V.S.', 'Vidsutnij');
insert into votes values(5067, 'Marmazov Ye.V.', 'Vidsutnij');
insert into votes values(5067, 'Martynyuk A.I.', 'Vidsutnij');
insert into votes values(5067, 'Martynyak S.V.', 'Za');
insert into votes values(5067, 'Marcinkiv R.R.', 'Za');
insert into votes values(5067, 'Matviyenkov S.A.', 'Vidsutnij');
insert into votes values(5067, 'Medunycya O.V.', 'Vidsutnij');
insert into votes values(5067, 'Mel"nyk Ye.I.', 'Za');
insert into votes values(5067, 'Mel"nychenko V.V.', 'Za');
insert into votes values(5067, 'Merikov V.I.', 'Za');
insert into votes values(5067, 'Myrnyj I.M.', 'Vidsutnij');
insert into votes values(5067, 'Myronenko M.I.', 'Ne holosuvav');
insert into votes values(5067, 'Myxajlenko O.D.', 'Vidsutnya');
insert into votes values(5067, 'Miroshnychenko I.M.', 'Za');
insert into votes values(5067, 'Mishhenko A.M.', 'Za');
insert into votes values(5067, 'Molotok I.F.', 'Vidsutnij');
insert into votes values(5067, 'Morozenko Ye.V.', 'Ne holosuvav');
insert into votes values(5067, 'Moskal" H.H.', 'Za');
insert into votes values(5067, 'Moshak S.M.', 'Vidsutnij');
insert into votes values(5067, 'Murayev Ye.V.', 'Vidsutnij');
insert into votes values(5067, 'Nakonechnyj V.L.', 'Vidsutnij');
insert into votes values(5067, 'Nemyrya H.M.', 'Za');
insert into votes values(5067, 'Netec"ka O.A.', 'Vidsutnya');
insert into votes values(5067, 'Nychyporenko V.M.', 'Za');
insert into votes values(5067, 'Novyns"kyj V.V.', 'Ne holosuvav');
insert into votes values(5067, 'Olijnyk V.M.', 'Vidsutnij');
insert into votes values(5067, 'Omel"yanovych D.S.', 'Vidsutnij');
insert into votes values(5067, 'Opanashhenko M.V.', 'Za');
insert into votes values(5067, 'Osaulenko T.V.', 'Za');
insert into votes values(5067, 'Osuxovs"kyj O.I.', 'Za');
insert into votes values(5067, 'Pavlenko R.M.', 'Za');
insert into votes values(5067, 'Pavlovs"kyj A.M.', 'Za');
insert into votes values(5067, 'Palamarchuk M.P.', 'Za');
insert into votes values(5067, 'Palycya I.P.', 'Vidsutnij');
insert into votes values(5067, 'Paraskiv O.D.', 'Vidsutnij');
insert into votes values(5067, 'Packan V.V.', 'Za');
insert into votes values(5067, 'Pet"ovka V.V.', 'Za');
insert into votes values(5067, 'Pylypenko V.P.', 'Vidsutnij');
insert into votes values(5067, 'Pynzenyk V.M.', 'Za');
insert into votes values(5067, 'Pyshnyj A.H.', 'Vidsutnij');
insert into votes values(5067, 'Pober I.M.', 'Za');
insert into votes values(5067, 'Polochaninov V.H.', 'Za');
insert into votes values(5067, 'Polyachenko Yu.V.', 'Vidsutnij');
insert into votes values(5067, 'Ponomar"ov O.S.', 'Za');
insert into votes values(5067, 'Poplavs"kyj M.M.', 'Vidsutnij');
insert into votes values(5067, 'Pryhods"kyj A.V.', 'Vidsutnij');
insert into votes values(5067, 'Prodan O.P.', 'Za');
insert into votes values(5067, 'Putilov A.S.', 'Vidsutnij');
insert into votes values(5067, 'Razvadovs"kyj V.J.', 'Za');
insert into votes values(5067, 'Revenko A.D.', 'Za');
insert into votes values(5067, 'Rybakov I.O.', 'Vidsutnij');
insert into votes values(5067, 'Rizanenko P.O.', 'Za');
insert into votes values(5067, 'Romanyuk R.S.', 'Za');
insert into votes values(5067, 'Ryabikin P.B.', 'Za');
insert into votes values(5067, 'Savchuk Yu.P.', 'Za');
insert into votes values(5067, 'Samojlenko V.P.', 'Vidsutnij');
insert into votes values(5067, 'Svyatash D.V.', 'Za');
insert into votes values(5067, 'Semenyuk A.O.', 'Vidsutnij');
insert into votes values(5067, 'Serhiyenko L.H.', 'Za');
insert into votes values(5067, 'Symonenko P.M.', 'Vidsutnij');
insert into votes values(5067, 'Sihal Ye.Ya.', 'Vidsutnij');
insert into votes values(5067, 'Skarbovijchuk R.V.', 'Vidsutnij');
insert into votes values(5067, 'Skubashevs"kyj S.V.', 'Vidsutnij');
insert into votes values(5067, 'Sobolyev S.V.', 'Za');
insert into votes values(5067, 'Sol"var R.M.', 'Za');
insert into votes values(5067, 'Spirina I.D.', 'Vidsutnya');
insert into votes values(5067, 'Stec" Yu.Ya.', 'Za');
insert into votes values(5067, 'Stoyan O.M.', 'Vidsutnij');
insert into votes values(5067, 'Stupak I.I.', 'Ne holosuvav');
insert into votes values(5067, 'Sushkevych V.M.', 'Za');
insert into votes values(5067, 'Tabalov O.M.', 'Ne holosuvav');
insert into votes values(5067, 'Tarasyuk B.I.', 'Za');
insert into votes values(5067, 'Ter"oxin S.A.', 'Za');
insert into votes values(5067, 'Tyxonov V.M.', 'Vidsutnij');
insert into votes values(5067, 'Tkachuk H.V.', 'Za');
insert into votes values(5067, 'Truxanov H.L.', 'Vidsutnij');
insert into votes values(5067, 'Turchynov O.V.', 'Za');
insert into votes values(5067, 'Tyahnybok O.Ya.', 'Za');
insert into votes values(5067, 'Fayermark S.O.', 'Za');
insert into votes values(5067, 'Fedoruk M.T.', 'Za');
insert into votes values(5067, 'Fedoryak H.D.', 'Za');
insert into votes values(5067, 'Fyshhuk O.H.', 'Za');
insert into votes values(5067, 'Furman O.Yu.', 'Za');
insert into votes values(5067, 'Xanenko S.M.', 'Za');
insert into votes values(5067, 'Xmil" M.M.', 'Za');
insert into votes values(5067, 'Car"ov O.A.', 'Vidsutnij');
insert into votes values(5067, 'Cyrkin I.M.', 'Ne holosuvav');
insert into votes values(5067, 'Chertkov Yu.D.', 'Vidsutnij');
insert into votes values(5067, 'Chorna H.M.', 'Za');
insert into votes values(5067, 'Chub V.Ye.', 'Vidsutnij');
insert into votes values(5067, 'Chuhunnikov V.S.', 'Za');
insert into votes values(5067, 'Chumak V.V.', 'Za');
insert into votes values(5067, 'Shapovalov Yu.A.', 'Za');
insert into votes values(5067, 'Shatvoryan V.H.', 'Vidsutnij');
insert into votes values(5067, 'Shevchenko A.V.', 'Za');
insert into votes values(5067, 'Shevchenko O.O.', 'Za');
insert into votes values(5067, 'Shencev D.O.', 'Vidsutnij');
insert into votes values(5067, 'Shkvarylyuk V.V.', 'Za');
insert into votes values(5067, 'Shlemko D.V.', 'Za');
insert into votes values(5067, 'Shuhalo R.V.', 'Vidsutnij');
insert into votes values(5067, 'Shufrych N.I.', 'Za');
insert into votes values(5067, 'Yavorivs"kyj V.O.', 'Za');
insert into votes values(5067, 'Yanukovych V.V.', 'Vidsutnij');
insert into votes values(5113, 'Abdullin O.R.', 'Za');
insert into votes values(5113, 'Azarov O.M.', 'Vidsutnij');
insert into votes values(5113, 'Andriyevs"kyj D.J.', 'Za');
insert into votes values(5113, 'Ar’yev V.I.', 'Za');
insert into votes values(5113, 'Atroshenko V.A.', 'Ne holosuvav');
insert into votes values(5113, 'Badayev R.H.', 'Ne holosuvav');
insert into votes values(5113, 'Bajsarov L.V.', 'Vidsutnij');
insert into votes values(5113, 'Balyc"kyj Ye.V.', 'Vidsutnij');
insert into votes values(5113, 'Baloha P.I.', 'Za');
insert into votes values(5113, 'Barvinenko V.D.', 'Ne holosuvav');
insert into votes values(5113, 'Bezbax Ya.Ya.', 'Za');
insert into votes values(5113, 'Berezhna I.H.', 'Vidsutnya');
insert into votes values(5113, 'Byel"kova O.V.', 'Za');
insert into votes values(5113, 'Bilyj O.P.', 'Vidsutnij');
insert into votes values(5113, 'Blavac"kyj M.V.', 'Za');
insert into votes values(5113, 'Blyznyuk A.M.', 'Ne holosuvav');
insert into votes values(5113, 'Bobov H.B.', 'Vidsutnij');
insert into votes values(5113, 'Bohoslovs"ka I.H.', 'Za');
insert into votes values(5113, 'Bojko V.B.', 'Za');
insert into votes values(5113, 'Bondar V.V.', 'Za');
insert into votes values(5113, 'Bondaryev K.A.', 'Za');
insert into votes values(5113, 'Boryta O.V.', 'Vidsutnya');
insert into votes values(5113, 'Boyars"kyj Yu.I.', 'Vidsutnij');
insert into votes values(5113, 'Bryhynec" O.M.', 'Ne holosuvav*');
insert into votes values(5113, 'Bublyk Yu.V.', 'Za');
insert into votes values(5113, 'Buryak S.V.', 'Za');
insert into votes values(5113, 'Buxovec" O.Yu.', 'Vidsutnij');
insert into votes values(5113, 'Vasadze T.Sh.', 'Ne holosuvav');
insert into votes values(5113, 'Vasyl"yev O.A.', 'Vidsutnij');
insert into votes values(5113, 'Vashhuk K.T.', 'Vidsutnya');
insert into votes values(5113, 'Vitiv A.M.', 'Za');
insert into votes values(5113, 'Voznyuk Yu.V.', 'Za');
insert into votes values(5113, 'Volkov O.M.', 'Ne holosuvav');
insert into votes values(5113, 'Hajdosh I.F.', 'Vidsutnij');
insert into votes values(5113, 'Helevej O.I.', 'Za');
insert into votes values(5113, 'Hereha O.V.', 'Vidsutnij');
insert into votes values(5113, 'Herman H.M.', 'Ne holosuvala');
insert into votes values(5113, 'Hinka Ya.Ya.', 'Za');
insert into votes values(5113, 'Hladij V.I.', 'Za');
insert into votes values(5113, 'Holovko V.A.', 'Za');
insert into votes values(5113, 'Holub O.V.', 'Vidsutnij');
insert into votes values(5113, 'Honcharov S.V.', 'Vidsutnij');
insert into votes values(5113, 'Horina I.A.', 'Vidsutnya');
insert into votes values(5113, 'Hrynevec"kyj S.R.', 'Vidsutnij');
insert into votes values(5113, 'Hryniv I.O.', 'Vidsutnij');
insert into votes values(5113, 'Hruba H.I.', 'Vidsutnij');
insert into votes values(5113, 'Hubar V.I.', 'Vidsutnij');
insert into votes values(5113, 'Hurvic E.J.', 'Za');
insert into votes values(5113, 'Dacenko L.M.', 'Za');
insert into votes values(5113, 'Demedyuk V.X.', 'Vidsutnij');
insert into votes values(5113, 'Demishkan V.F.', 'Za');
insert into votes values(5113, 'Denysenko A.P.', 'Za');
insert into votes values(5113, 'Derev’yanko Yu.B.', 'Za');
insert into votes values(5113, 'Dzhemilyev M. .', 'Ne holosuvav');
insert into votes values(5113, 'Dzardanov M.S.', 'Vidsutnij');
insert into votes values(5113, 'Dzoz V.O.', 'Vidsutnya');
insert into votes values(5113, 'Dmytruk M.I.', 'Ne holosuvav');
insert into votes values(5113, 'Dolzhenkov O.V.', 'Vidsutnij');
insert into votes values(5113, 'Donec" T.A.', 'Ne holosuvala');
insert into votes values(5113, 'Doroxov A.M.', 'Vidsutnij');
insert into votes values(5113, 'Dubnevych Ya.V.', 'Za');
insert into votes values(5113, 'Dudka V.V.', 'Za');
insert into votes values(5113, 'Dunayev S.V.', 'Vidsutnij');
insert into votes values(5113, 'Yedin O.J.', 'Ne holosuvav*');
insert into votes values(5113, 'Yeremeyev I.M.', 'Vidsutnij');
insert into votes values(5113, 'Zhvaniya D.V.', 'Ne holosuvav');
insert into votes values(5113, 'Zherebnyuk V.M.', 'Vidsutnij');
insert into votes values(5113, 'Zhuravs"kyj V.S.', 'Za');
insert into votes values(5113, 'Zabolotnyj H.M.', 'Ne holosuvav');
insert into votes values(5113, 'Zarubins"kyj O.O.', 'Za');
insert into votes values(5113, 'Zvyahil"s"kyj Yu.L.', 'Za');
insert into votes values(5113, 'Zubyk V.V.', 'Vidsutnij');
insert into votes values(5113, 'Zubchevs"kyj O.P.', 'Vidsutnij');
insert into votes values(5113, 'Ivanyushhenko Yu.V.', 'Vidsutnij');
insert into votes values(5113, 'Ilyk R.R.', 'Za');
insert into votes values(5113, 'Il"yuk A.O.', 'Ne holosuvav');
insert into votes values(5113, 'Ionova M.M.', 'Za');
insert into votes values(5113, 'Ishhenko V.O.', 'Za');
insert into votes values(5113, 'Kaletnyk O.M.', 'Vidsutnya');
insert into votes values(5113, 'Kalyetnik I.H.', 'Vidsutnij');
insert into votes values(5113, 'Kal"chenko V.M.', 'Za');
insert into votes values(5113, 'Kanivec" O.L.', 'Za');
insert into votes values(5113, 'Karpuncov V.V.', 'Za');
insert into votes values(5113, 'Katerynchuk M.D.', 'Za');
insert into votes values(5113, 'Kacuba S.V.', 'Za');
insert into votes values(5113, 'Kyrylenko V.A.', 'Za');
insert into votes values(5113, 'Kyrylenko P.V.', 'Za');
insert into votes values(5113, 'Kilinkarov S.P.', 'Vidsutnij');
insert into votes values(5113, 'Kisse A.I.', 'Vidsutnij');
insert into votes values(5113, 'Klyuyev S.P.', 'Vidsutnij');
insert into votes values(5113, 'Knyazevych R.P.', 'Za');
insert into votes values(5113, 'Koval"chuk V.A.', 'Za');
insert into votes values(5113, 'Kozhem’yakin A.A.', 'Za');
insert into votes values(5113, 'Kolhanova O.V.', 'Za');
insert into votes values(5113, 'Kondratyuk O.K.', 'Za');
insert into votes values(5113, 'Korzhev A.L.', 'Vidsutnij');
insert into votes values(5113, 'Korolyuk V.A.', 'Za');
insert into votes values(5113, 'Koshulyns"kyj R.V.', 'Za');
insert into votes values(5113, 'Kryvec"kyj I.I.', 'Za');
insert into votes values(5113, 'Kruk Yu.B.', 'Za');
insert into votes values(5113, 'Kudrya V.I.', 'Vidsutnij');
insert into votes values(5113, 'Kuz"menko S.A.', 'Za');
insert into votes values(5113, 'Kulinich O.I.', 'Za');
insert into votes values(5113, 'Kunchenko O.P.', 'Vidsutnij');
insert into votes values(5113, 'Kupchak V.R.', 'Za');
insert into votes values(5113, 'Kurovs"kyj I.I.', 'Za');
insert into votes values(5113, 'Kutovyj V.H.', 'Za');
insert into votes values(5113, 'Kucheruk M.H.', 'Za');
insert into votes values(5113, 'Labuns"ka A.V.', 'Ne holosuvala');
insert into votes values(5113, 'Lan"o M.I.', 'Vidsutnij');
insert into votes values(5113, 'Levchenko O.V.', 'Vidsutnya');
insert into votes values(5113, 'Lelyuk O.V.', 'Vidsutnij');
insert into votes values(5113, 'Lytvyn V.M.', 'Vidsutnij');
insert into votes values(5113, 'Lopachak M.R.', 'Za');
insert into votes values(5113, 'Luk’yanov V.V.', 'Vidsutnij');
insert into votes values(5113, 'Lunchenko V.V.', 'Za');
insert into votes values(5113, 'L"ovochkina Yu.V.', 'Vidsutnya');
insert into votes values(5113, 'Lyutikova V.I.', 'Vidsutnya');
insert into votes values(5113, 'Lyashko O.V.', 'Za');
insert into votes values(5113, 'Makul L.Ya.', 'Za');
insert into votes values(5113, 'Mal"cev V.O.', 'Vidsutnij');
insert into votes values(5113, 'Martynenko M.V.', 'Za');
insert into votes values(5113, 'Martynyuk L.S.', 'Za');
insert into votes values(5113, 'Martovyc"kyj A.V.', 'Vidsutnij');
insert into votes values(5113, 'Matvyeyev V.H.', 'Vidsutnij');
insert into votes values(5113, 'Matios M.V.', 'Ne holosuvala');
insert into votes values(5113, 'Medyanyk V.Yu.', 'Vidsutnij');
insert into votes values(5113, 'Mel"nyk S.A.', 'Za');
insert into votes values(5113, 'Mel"nychuk L.Yu.', 'Za');
insert into votes values(5113, 'Myryms"kyj L.Yu.', 'Za');
insert into votes values(5113, 'Myrnyj O.B.', 'Za');
insert into votes values(5113, 'Mysyk V.Yu.', 'Vidsutnij');
insert into votes values(5113, 'Myxal"chyshyn Yu.A.', 'Za');
insert into votes values(5113, 'Miroshnychenko Yu.R.', 'Vidsutnij');
insert into votes values(5113, 'Mishhenko S.H.', 'Za');
insert into votes values(5113, 'Momot O.I.', 'Vidsutnij');
insert into votes values(5113, 'Moskalenko Ya.M.', 'Ne holosuvav');
insert into votes values(5113, 'Mochkov O.B.', 'Za');
insert into votes values(5113, 'Moshens"kyj V.Z.', 'Ne holosuvav');
insert into votes values(5113, 'Mxitaryan N.M.', 'Za');
insert into votes values(5113, 'Nehoj F.F.', 'Za');
insert into votes values(5113, 'Nemilostivyj V.O.', 'Za');
insert into votes values(5113, 'Nechayev O.I.', 'Vidsutnij');
insert into votes values(5113, 'Novak N.V.', 'Za');
insert into votes values(5113, 'Odarchenko Yu.V.', 'Za');
insert into votes values(5113, 'Omel"chenko V.P.', 'Vidsutnij');
insert into votes values(5113, 'Onyshhenko O.R.', 'Vidsutnij');
insert into votes values(5113, 'Orobec" L.Yu.', 'Vidsutnya');
insert into votes values(5113, 'Ostapchuk V.M.', 'Ne holosuvav');
insert into votes values(5113, 'Pavelko A.V.', 'Za');
insert into votes values(5113, 'Pavlov K.Yu.', 'Vidsutnij');
insert into votes values(5113, 'Pazynyak V.S.', 'Za');
insert into votes values(5113, 'Palatnyj A.L.', 'Za');
insert into votes values(5113, 'Pan"kevych O.I.', 'Za');
insert into votes values(5113, 'Parubok O.N.', 'Vidsutnij');
insert into votes values(5113, 'Pashyns"kyj S.V.', 'Za');
insert into votes values(5113, 'Pexov V.A.', 'Za');
insert into votes values(5113, 'Pylypyshyn V.P.', 'Vidsutnij');
insert into votes values(5113, 'Pysarenko V.V.', 'Vidsutnij');
insert into votes values(5113, 'Pinchuk A.P.', 'Za');
insert into votes values(5113, 'Povalij T.M.', 'Vidsutnya');
insert into votes values(5113, 'Polyakov V.L.', 'Za');
insert into votes values(5113, 'Ponomar"ov A.V.', 'Vidsutnij');
insert into votes values(5113, 'Popesku I.V.', 'Za');
insert into votes values(5113, 'Presman O.S.', 'Ne holosuvav');
insert into votes values(5113, 'Prysyazhnyuk O.A.', 'Vidsutnij');
insert into votes values(5113, 'Prodyvus V.S.', 'Vidsutnij');
insert into votes values(5113, 'Pshonka A.V.', 'Vidsutnij');
insert into votes values(5113, 'Raupov R.B.', 'Za');
insert into votes values(5113, 'Rybak V.V.', 'Za');
insert into votes values(5113, 'Ryzhenkov O.M.', 'Vidsutnij');
insert into votes values(5113, 'Rozenko P.V.', 'Za');
insert into votes values(5113, 'Rud"kovs"kyj M.M.', 'Za');
insert into votes values(5113, 'Sabij I.M.', 'Za');
insert into votes values(5113, 'Sal"do V.V.', 'Za');
insert into votes values(5113, 'Samojlenko Yu.P.', 'Vidsutnij');
insert into votes values(5113, 'Selivarov A.B.', 'Vidsutnij');
insert into votes values(5113, 'Senchenko A.V.', 'Za');
insert into votes values(5113, 'Sex I.I.', 'Za');
insert into votes values(5113, 'Syrotyuk Yu.M.', 'Za');
insert into votes values(5113, 'Sikora O.M.', 'Za');
insert into votes values(5113, 'Skosar I.Ye.', 'Vidsutnij');
insert into votes values(5113, 'Smityux H.Ye.', 'Ne holosuvav');
insert into votes values(5113, 'Soloshenko M.P.', 'Vidsutnij');
insert into votes values(5113, 'Soroka M.P.', 'Ne holosuvav');
insert into votes values(5113, 'Stadnijchuk R.V.', 'Vidsutnij');
insert into votes values(5113, 'Stojko I.M.', 'Za');
insert into votes values(5113, 'Struk V.O.', 'Vidsutnij');
insert into votes values(5113, 'Suxyj Ya.M.', 'Vidsutnij');
insert into votes values(5113, 'Tabalov A.O.', 'Za');
insert into votes values(5113, 'Tabachnik Ya.P.', 'Za');
insert into votes values(5113, 'Tedeyev E.S.', 'Vidsutnij');
insert into votes values(5113, 'Tymoshenko V.A.', 'Ne holosuvav');
insert into votes values(5113, 'Tihipko S.L.', 'Za');
insert into votes values(5113, 'Tomenko M.V.', 'Za');
insert into votes values(5113, 'Turmanov V.I.', 'Vidsutnij');
insert into votes values(5113, 'Tyahnybok A.Ya.', 'Za');
insert into votes values(5113, 'Fabrykant S.S.', 'Za');
insert into votes values(5113, 'Farion I.D.', 'Za');
insert into votes values(5113, 'Fedorchuk Ya.P.', 'Za');
insert into votes values(5113, 'Fel"dman O.B.', 'Za');
insert into votes values(5113, 'Firsov Ye.P.', 'Za');
insert into votes values(5113, 'Fursin I.H.', 'Vidsutnij');
insert into votes values(5113, 'Xmel"nyc"kyj V.I.', 'Vidsutnij');
insert into votes values(5113, 'Xomutynnik V.Yu.', 'Ne holosuvav');
insert into votes values(5113, 'Cybenko P.S.', 'Vidsutnij');
insert into votes values(5113, 'Cherneha R.T.', 'Za');
insert into votes values(5113, 'Chechetov M.V.', 'Vidsutnij');
insert into votes values(5113, 'Chornovolenko O.V.', 'Za');
insert into votes values(5113, 'Chubatenko O.M.', 'Ne holosuvav');
insert into votes values(5113, 'Chudnovs"kyj V.O.', 'Za');
insert into votes values(5113, 'Shablatovych O.M.', 'Za');
insert into votes values(5113, 'Sharov I.F.', 'Za');
insert into votes values(5113, 'Shvec" V.D.', 'Za');
insert into votes values(5113, 'Shevchenko O.L.', 'Za');
insert into votes values(5113, 'Shevchuk O.B.', 'Za');
insert into votes values(5113, 'Shypko A.F.', 'Za');
insert into votes values(5113, 'Shkirya I.M.', 'Za');
insert into votes values(5113, 'Shpenov D.Yu.', 'Vidsutnij');
insert into votes values(5113, 'Shul"ha V.P.', 'Za');
insert into votes values(5113, 'Shherban" A.V.', 'Za');
insert into votes values(5113, 'Yankiv I.T.', 'Za');
insert into votes values(5113, 'Yacenko A.V.', 'Ne holosuvav');
insert into votes values(5113, 'Ahafonova N.V.', 'Vidsutnya');
insert into votes values(5113, 'Aleksyeyev I.V.', 'Vidsutnij');
insert into votes values(5113, 'Apostol M.V.', 'Za');
insert into votes values(5113, 'Arkallayev N.H.', 'Vidsutnij');
insert into votes values(5113, 'Bahrayev M.H.', 'Za');
insert into votes values(5113, 'Bajdyuk L.M.', 'Vidsutnya');
insert into votes values(5113, 'Balandin S.V.', 'Vidsutnij');
insert into votes values(5113, 'Baloha V.I.', 'Za');
insert into votes values(5113, 'Bandurov V.V.', 'Vidsutnij');
insert into votes values(5113, 'Baxteyeva T.D.', 'Za');
insert into votes values(5113, 'Benyuk B.M.', 'Za');
insert into votes values(5113, 'Berezkin S.S.', 'Za');
insert into votes values(5113, 'Bid"ovka V.A.', 'Vidsutnij');
insert into votes values(5113, 'Bilovol O.M.', 'Za');
insert into votes values(5113, 'Blahodyr Yu.A.', 'Vidsutnij');
insert into votes values(5113, 'Bobkov O.M.', 'Vidsutnij');
insert into votes values(5113, 'Bohdan R.D.', 'Za');
insert into votes values(5113, 'Bohuslayev V.O.', 'Vidsutnij');
insert into votes values(5113, 'Bojko V.S.', 'Vidsutnij');
insert into votes values(5113, 'Bondarenko O.A.', 'Vidsutnya');
insert into votes values(5113, 'Bondarchuk O.V.', 'Za');
insert into votes values(5113, 'Bort V.P.', 'Ne holosuvav');
insert into votes values(5113, 'Brajko S.B.', 'Vidsutnij');
insert into votes values(5113, 'Brychenko I.V.', 'Za');
insert into votes values(5113, 'Bulax V.V.', 'Vidsutnya');
insert into votes values(5113, 'Butkivs"kyj V.V.', 'Vidsutnij');
insert into votes values(5113, 'Bushko I.I.', 'Vidsutnij');
insert into votes values(5113, 'Vasyl"yev H.A.', 'Vidsutnij');
insert into votes values(5113, 'Vasyunyk I.V.', 'Za');
insert into votes values(5113, 'Vecherko V.M.', 'Za');
insert into votes values(5113, 'Vlasenko S.V.', 'Za');
insert into votes values(5113, 'Volkov O.A.', 'Za');
insert into votes values(5113, 'Voropayev Yu.M.', 'Ne holosuvav');
insert into votes values(5113, 'Hanchukov O.K.', 'Vidsutnij');
insert into votes values(5113, 'Herashhenko I.V.', 'Za');
insert into votes values(5113, 'Herzhov Yu.I.', 'Ne holosuvav');
insert into votes values(5113, 'Hyellyer Ye.B.', 'Vidsutnij');
insert into votes values(5113, 'Hirshfel"d A.M.', 'Vidsutnij');
insert into votes values(5113, 'Hlazunov S.M.', 'Vidsutnij');
insert into votes values(5113, 'Holovko M.J.', 'Za');
insert into votes values(5113, 'Honcharov A.D.', 'Vidsutnij');
insert into votes values(5113, 'Hordiyenko S.V.', 'Vidsutnij');
insert into votes values(5113, 'Horoxov S.O.', 'Vidsutnij');
insert into votes values(5113, 'Hrynevych L.M.', 'Za');
insert into votes values(5113, 'Hrycenko A.S.', 'Za');
insert into votes values(5113, 'Hrushevs"kyj V.A.', 'Ne holosuvav');
insert into votes values(5113, 'Huzenko K.O.', 'Vidsutnij');
insert into votes values(5113, 'Danilov V.B.', 'Za');
insert into votes values(5113, 'Dejch B.D.', 'Vidsutnij');
insert into votes values(5113, 'Demydko V.M.', 'Vidsutnij');
insert into votes values(5113, 'Demyanko M.I.', 'Vidsutnij');
insert into votes values(5113, 'Derevlyanyj V.T.', 'Za');
insert into votes values(5113, 'Derkach A.L.', 'Vidsutnij');
insert into votes values(5113, 'Dzhyha M.V.', 'Za');
insert into votes values(5113, 'Dzenzers"kyj D.V.', 'Za');
insert into votes values(5113, 'Dyriv A.B.', 'Za');
insert into votes values(5113, 'Dobkin D.M.', 'Vidsutnij');
insert into votes values(5113, 'Dombrovs"kyj O.H.', 'Za');
insert into votes values(5113, 'Donij O.S.', 'Za');
insert into votes values(5113, 'Dubil" V.O.', 'Za');
insert into votes values(5113, 'Dubovoj O.F.', 'Za');
insert into votes values(5113, 'Dudka O.I.', 'Za');
insert into votes values(5113, 'Yehorov O.M.', 'Vidsutnij');
insert into votes values(5113, 'Yemec" L.O.', 'Za');
insert into votes values(5113, 'Yefremov O.S.', 'Vidsutnij');
insert into votes values(5113, 'Zhevaho K.V.', 'Vidsutnij');
insert into votes values(5113, 'Zhuk M.V.', 'Ne holosuvav');
insert into votes values(5113, 'Zabzalyuk R.O.', 'Vidsutnij');
insert into votes values(5113, 'Zadorozhnyj V.K.', 'Vidsutnij');
insert into votes values(5113, 'Zac O.V.', 'Vidsutnij');
insert into votes values(5113, 'Zelyk R.B.', 'Za');
insert into votes values(5113, 'Zubko H.H.', 'Za');
insert into votes values(5113, 'Ivanchuk A.V.', 'Za');
insert into votes values(5113, 'Ivaxiv S.P.', 'Za');
insert into votes values(5113, 'Illyenko A.Yu.', 'Za');
insert into votes values(5113, 'Ilyashenko V.V.', 'Za');
insert into votes values(5113, 'Ioffe Yu.Ya.', 'Vidsutnij');
insert into votes values(5113, 'Kajda O.P.', 'Za');
insert into votes values(5113, 'Kaletnik H.M.', 'Vidsutnij');
insert into votes values(5113, 'Kal"cev S.F.', 'Za');
insert into votes values(5113, 'Kalyuzhnyj V.A.', 'Vidsutnij');
insert into votes values(5113, 'Kaplin S.M.', 'Za');
insert into votes values(5113, 'Kartashov Ye.H.', 'Za');
insert into votes values(5113, 'Kacuba V.M.', 'Za');
insert into votes values(5113, 'Kyj S.V.', 'Vidsutnij');
insert into votes values(5113, 'Kyrylenko I.H.', 'Za');
insert into votes values(5113, 'Kivalov S.V.', 'Za');
insert into votes values(5113, 'Kinax A.K.', 'Za');
insert into votes values(5113, 'Klimov L.M.', 'Ne holosuvav');
insert into votes values(5113, 'Knyazhyc"kyj M.L.', 'Za');
insert into votes values(5113, 'Koval" O.I.', 'Vidsutnij');
insert into votes values(5113, 'Kovach V.I.', 'Ne holosuvav');
insert into votes values(5113, 'Kozub O.A.', 'Ne holosuvav');
insert into votes values(5113, 'Kolesnikov B.V.', 'Vidsutnij');
insert into votes values(5113, 'Korzh P.P.', 'Vidsutnij');
insert into votes values(5113, 'Kornijchuk O.O.', 'Ne holosuvav');
insert into votes values(5113, 'Kotelyak L.L.', 'Za');
insert into votes values(5113, 'Kravchuk V.P.', 'Vidsutnij');
insert into votes values(5113, 'Kruhlov M.P.', 'Za');
insert into votes values(5113, 'Krutij V.I.', 'Za');
insert into votes values(5113, 'Kuzhel" O.V.', 'Za');
insert into votes values(5113, 'Kuz"muk O.I.', 'Za');
insert into votes values(5113, 'Kunicyn S.V.', 'Za');
insert into votes values(5113, 'Kuprejchyk I.V.', 'Za');
insert into votes values(5113, 'Kurennoj V.K.', 'Ne holosuvav');
insert into votes values(5113, 'Kurpil" S.V.', 'Za');
insert into votes values(5113, 'Kutovyj T.V.', 'Za');
insert into votes values(5113, 'Labazyuk S.P.', 'Vidsutnij');
insert into votes values(5113, 'Landyk V.I.', 'Vidsutnij');
insert into votes values(5113, 'Levchenko M.O.', 'Vidsutnij');
insert into votes values(5113, 'Ledovs"kyx O.V.', 'Za');
insert into votes values(5113, 'Leonov E.V.', 'Za');
insert into votes values(5113, 'Lytvynov L.F.', 'Vidsutnij');
insert into votes values(5113, 'Lukashuk O.H.', 'Za');
insert into votes values(5113, 'Luk’yanchuk R.V.', 'Za');
insert into votes values(5113, 'Lucenko I.S.', 'Za');
insert into votes values(5113, 'Lyubonenko Yu.V.', 'Vidsutnij');
insert into votes values(5113, 'Lyapina K.M.', 'Za');
insert into votes values(5113, 'Makeyenko V.V.', 'Za');
insert into votes values(5113, 'Malyshev V.S.', 'Vidsutnij');
insert into votes values(5113, 'Marmazov Ye.V.', 'Vidsutnij');
insert into votes values(5113, 'Martynyuk A.I.', 'Vidsutnij');
insert into votes values(5113, 'Martynyak S.V.', 'Za');
insert into votes values(5113, 'Marcinkiv R.R.', 'Za');
insert into votes values(5113, 'Matviyenkov S.A.', 'Vidsutnij');
insert into votes values(5113, 'Medunycya O.V.', 'Za');
insert into votes values(5113, 'Mel"nyk Ye.I.', 'Za');
insert into votes values(5113, 'Mel"nychenko V.V.', 'Za');
insert into votes values(5113, 'Merikov V.I.', 'Za');
insert into votes values(5113, 'Myrnyj I.M.', 'Vidsutnij');
insert into votes values(5113, 'Myronenko M.I.', 'Za');
insert into votes values(5113, 'Myxajlenko O.D.', 'Vidsutnya');
insert into votes values(5113, 'Miroshnychenko I.M.', 'Za');
insert into votes values(5113, 'Mishhenko A.M.', 'Za');
insert into votes values(5113, 'Molotok I.F.', 'Za');
insert into votes values(5113, 'Morozenko Ye.V.', 'Ne holosuvav');
insert into votes values(5113, 'Moskal" H.H.', 'Za');
insert into votes values(5113, 'Moshak S.M.', 'Vidsutnij');
insert into votes values(5113, 'Murayev Ye.V.', 'Vidsutnij');
insert into votes values(5113, 'Nakonechnyj V.L.', 'Vidsutnij');
insert into votes values(5113, 'Nemyrya H.M.', 'Za');
insert into votes values(5113, 'Netec"ka O.A.', 'Vidsutnya');
insert into votes values(5113, 'Nychyporenko V.M.', 'Za');
insert into votes values(5113, 'Novyns"kyj V.V.', 'Ne holosuvav');
insert into votes values(5113, 'Olijnyk V.M.', 'Vidsutnij');
insert into votes values(5113, 'Omel"yanovych D.S.', 'Vidsutnij');
insert into votes values(5113, 'Opanashhenko M.V.', 'Vidsutnij');
insert into votes values(5113, 'Osaulenko T.V.', 'Za');
insert into votes values(5113, 'Osuxovs"kyj O.I.', 'Za');
insert into votes values(5113, 'Pavlenko R.M.', 'Za');
insert into votes values(5113, 'Pavlovs"kyj A.M.', 'Za');
insert into votes values(5113, 'Palamarchuk M.P.', 'Za');
insert into votes values(5113, 'Palycya I.P.', 'Vidsutnij');
insert into votes values(5113, 'Paraskiv O.D.', 'Vidsutnij');
insert into votes values(5113, 'Packan V.V.', 'Ne holosuvav');
insert into votes values(5113, 'Pet"ovka V.V.', 'Za');
insert into votes values(5113, 'Pylypenko V.P.', 'Za');
insert into votes values(5113, 'Pynzenyk V.M.', 'Za');
insert into votes values(5113, 'Pyshnyj A.H.', 'Vidsutnij');
insert into votes values(5113, 'Pober I.M.', 'Ne holosuvav');
insert into votes values(5113, 'Polochaninov V.H.', 'Za');
insert into votes values(5113, 'Polyachenko Yu.V.', 'Vidsutnij');
insert into votes values(5113, 'Ponomar"ov O.S.', 'Vidsutnij');
insert into votes values(5113, 'Poplavs"kyj M.M.', 'Vidsutnij');
insert into votes values(5113, 'Pryhods"kyj A.V.', 'Vidsutnij');
insert into votes values(5113, 'Prodan O.P.', 'Vidsutnya');
insert into votes values(5113, 'Putilov A.S.', 'Vidsutnij');
insert into votes values(5113, 'Razvadovs"kyj V.J.', 'Za');
insert into votes values(5113, 'Revenko A.D.', 'Za');
insert into votes values(5113, 'Rybakov I.O.', 'Vidsutnij');
insert into votes values(5113, 'Rizanenko P.O.', 'Za');
insert into votes values(5113, 'Romanyuk R.S.', 'Za');
insert into votes values(5113, 'Ryabikin P.B.', 'Za');
insert into votes values(5113, 'Savchuk Yu.P.', 'Za');
insert into votes values(5113, 'Samojlenko V.P.', 'Vidsutnij');
insert into votes values(5113, 'Svyatash D.V.', 'Za');
insert into votes values(5113, 'Semenyuk A.O.', 'Vidsutnij');
insert into votes values(5113, 'Serhiyenko L.H.', 'Vidsutnij');
insert into votes values(5113, 'Symonenko P.M.', 'Vidsutnij');
insert into votes values(5113, 'Sihal Ye.Ya.', 'Vidsutnij');
insert into votes values(5113, 'Skarbovijchuk R.V.', 'Vidsutnij');
insert into votes values(5113, 'Skubashevs"kyj S.V.', 'Vidsutnij');
insert into votes values(5113, 'Sobolyev S.V.', 'Za');
insert into votes values(5113, 'Sol"var R.M.', 'Za');
insert into votes values(5113, 'Spirina I.D.', 'Vidsutnya');
insert into votes values(5113, 'Stec" Yu.Ya.', 'Za');
insert into votes values(5113, 'Stoyan O.M.', 'Za');
insert into votes values(5113, 'Stupak I.I.', 'Vidsutnij');
insert into votes values(5113, 'Sushkevych V.M.', 'Za');
insert into votes values(5113, 'Tabalov O.M.', 'Ne holosuvav');
insert into votes values(5113, 'Tarasyuk B.I.', 'Za');
insert into votes values(5113, 'Ter"oxin S.A.', 'Za');
insert into votes values(5113, 'Tyxonov V.M.', 'Vidsutnij');
insert into votes values(5113, 'Tkachuk H.V.', 'Za');
insert into votes values(5113, 'Truxanov H.L.', 'Vidsutnij');
insert into votes values(5113, 'Turchynov O.V.', 'Za');
insert into votes values(5113, 'Tyahnybok O.Ya.', 'Za');
insert into votes values(5113, 'Fayermark S.O.', 'Za');
insert into votes values(5113, 'Fedoruk M.T.', 'Za');
insert into votes values(5113, 'Fedoryak H.D.', 'Vidsutnij');
insert into votes values(5113, 'Fyshhuk O.H.', 'Za');
insert into votes values(5113, 'Furman O.Yu.', 'Za');
insert into votes values(5113, 'Xanenko S.M.', 'Za');
insert into votes values(5113, 'Xmil" M.M.', 'Za');
insert into votes values(5113, 'Car"ov O.A.', 'Vidsutnij');
insert into votes values(5113, 'Cyrkin I.M.', 'Ne holosuvav');
insert into votes values(5113, 'Chertkov Yu.D.', 'Vidsutnij');
insert into votes values(5113, 'Chorna H.M.', 'Za');
insert into votes values(5113, 'Chub V.Ye.', 'Vidsutnij');
insert into votes values(5113, 'Chuhunnikov V.S.', 'Za');
insert into votes values(5113, 'Chumak V.V.', 'Za');
insert into votes values(5113, 'Shapovalov Yu.A.', 'Za');
insert into votes values(5113, 'Shatvoryan V.H.', 'Vidsutnij');
insert into votes values(5113, 'Shevchenko A.V.', 'Za');
insert into votes values(5113, 'Shevchenko O.O.', 'Za');
insert into votes values(5113, 'Shencev D.O.', 'Vidsutnij');
insert into votes values(5113, 'Shkvarylyuk V.V.', 'Za');
insert into votes values(5113, 'Shlemko D.V.', 'Za');
insert into votes values(5113, 'Shuhalo R.V.', 'Vidsutnij');
insert into votes values(5113, 'Shufrych N.I.', 'Za');
insert into votes values(5113, 'Yavorivs"kyj V.O.', 'Za');
insert into votes values(5113, 'Yanukovych V.V.', 'Vidsutnij');
insert into votes values(2763, 'Abdullin O.R.', 'Za');
insert into votes values(2763, 'Aleksyeyev I.V.', 'Za');
insert into votes values(2763, 'Arzhevitin S.M.', 'Za');
insert into votes values(2763, 'Arutyunov H.R.', 'Za');
insert into votes values(2763, 'Babayev O.M.', 'Za');
insert into votes values(2763, 'Baburin O.V.', 'Za');
insert into votes values(2763, 'Baranov V.O.', 'Za');
insert into votes values(2763, 'Baxteyeva T.D.', 'Za');
insert into votes values(2763, 'Bevzenko V.F.', 'Ne holosuvav');
insert into votes values(2763, 'Berezhna I.H.', 'Za');
insert into votes values(2763, 'Bilozir O.V.', 'Ne holosuvala');
insert into votes values(2763, 'Biryuk L.V.', 'Za');
insert into votes values(2763, 'Bohdan R.D.', 'Za');
insert into votes values(2763, 'Bohuslayev V.O.', 'Za');
insert into votes values(2763, 'Boldyryev Yu.O.', 'Za');
insert into votes values(2763, 'Bondar O.M.', 'Za');
insert into votes values(2763, 'Bondarenko V.D.', 'Za');
insert into votes values(2763, 'Bondarenko O.F.', 'Za');
insert into votes values(2763, 'Bondyk V.A.', 'Ne holosuvav');
insert into votes values(2763, 'Borodin V.V.', 'Za');
insert into votes values(2763, 'Boyarchuk O.V.', 'Za');
insert into votes values(2763, 'Buryak O.V.', 'Za');
insert into votes values(2763, 'Vasadze T.Sh.', 'Za');
insert into votes values(2763, 'Vasyl"yev H.A.', 'Za');
insert into votes values(2763, 'Vasyutin S.I.', 'Za');
insert into votes values(2763, 'Velizhans"kyj S.K.', 'Za');
insert into votes values(2763, 'Kalyetnik I.H.', 'Za');
insert into votes values(2763, 'Kalyuzhnyj V.A.', 'Ne holosuvav');
insert into votes values(2763, 'Kapliyenko V.V.', 'Za');
insert into votes values(2763, 'Karmazin Yu.A.', 'Za');
insert into votes values(2763, 'Kas"kiv V.V.', 'Za');
insert into votes values(2763, 'Katerynchuk M.D.', 'Za');
insert into votes values(2763, 'Kemenyash O.M.', 'Za');
insert into votes values(2763, 'Kyj S.V.', 'Za');
insert into votes values(2763, 'Kyrylenko I.H.', 'Za');
insert into votes values(2763, 'Kyrychok O.E.', 'Za');
insert into votes values(2763, 'Kivalov S.V.', 'Za');
insert into votes values(2763, 'Kinax A.K.', 'Za');
insert into votes values(2763, 'Klymec" P.A.', 'Za');
insert into votes values(2763, 'Klyuyev S.P.', 'Za');
insert into votes values(2763, 'Knyazevych R.P.', 'Za');
insert into votes values(2763, 'Koval" V.S.', 'Za');
insert into votes values(2763, 'Kovzel" M.O.', 'Za');
insert into votes values(2763, 'Kozhem’yakin A.A.', 'Za');
insert into votes values(2763, 'Kozub O.A.', 'Za');
insert into votes values(2763, 'Kolocej Yu.O.', 'Za');
insert into votes values(2763, 'Kondratyuk O.K.', 'Za');
insert into votes values(2763, 'Konstantynov Ye.S.', 'Za');
insert into votes values(2763, 'Korzh V.T.', 'Za');
insert into votes values(2763, 'Korzhev A.L.', 'Za');
insert into votes values(2763, 'Korotyuk V.I.', 'Za');
insert into votes values(2763, 'Kostenko P.I.', 'Za');
insert into votes values(2763, 'Koshyn S.M.', 'Za');
insert into votes values(2763, 'Kravchuk V.P.', 'Za');
insert into votes values(2763, 'Kril" I.I.', 'Za');
insert into votes values(2763, 'Kruc" M.F.', 'Ne holosuvav');
insert into votes values(2763, 'Kuz"muk O.I.', 'Za');
insert into votes values(2763, 'Kul"chyns"kyj M.H.', 'Za');
insert into votes values(2763, 'Kurylo V.S.', 'Za');
insert into votes values(2763, 'Kurpil" S.V.', 'Za');
insert into votes values(2763, 'Landyk V.I.', 'Za');
insert into votes values(2763, 'Lebedyev P.V.', 'Za');
insert into votes values(2763, 'Lelyuk O.V.', 'Za');
insert into votes values(2763, 'Lyeshhyns"kyj O.O.', 'Za');
insert into votes values(2763, 'Lytvyn V.M.', 'Ne holosuvav');
insert into votes values(2763, 'Lytvynov L.F.', 'Za');
insert into votes values(2763, 'Lisin M.P.', 'Za');
insert into votes values(2763, 'Lukashuk O.H.', 'Za');
insert into votes values(2763, 'Luk’yanova K.Ye.', 'Ne holosuvala');
insert into votes values(2763, 'Luc"kyj M.H.', 'Za');
insert into votes values(2763, 'Lyapina K.M.', 'Ne holosuvala');
insert into votes values(2763, 'Majboroda S.F.', 'Za');
insert into votes values(2763, 'Makiyenko V.P.', 'Za');
insert into votes values(2763, 'Malich O.V.', 'Za');
insert into votes values(2763, 'Man"kovs"kyj H.V.', 'Za');
insert into votes values(2763, 'Martynenko M.V.', 'Za');
insert into votes values(2763, 'Marushhenko V.S.', 'Ne holosuvav');
insert into votes values(2763, 'Matvyeyev V.J.', 'Za');
insert into votes values(2763, 'Matchuk V.J.', 'Vidsutnij');
insert into votes values(2763, 'Mel"nyk S.A.', 'Za');
insert into votes values(2763, 'Myronenko M.I.', 'Za');
insert into votes values(2763, 'Mishhenko S.H.', 'Za');
insert into votes values(2763, 'Mojsyk V.R.', 'Za');
insert into votes values(2763, 'Moroko Yu.M.', 'Ne holosuvav');
insert into votes values(2763, 'Mostipan U.M.', 'Za');
insert into votes values(2763, 'Muc O.P.', 'Za');
insert into votes values(2763, 'Nadosha O.V.', 'Za');
insert into votes values(2763, 'Nakonechnyj V.L.', 'Za');
insert into votes values(2763, 'Odarchenko Yu.V.', 'Za');
insert into votes values(2763, 'Olijnyk V.M.', 'Za');
insert into votes values(2763, 'Omel"chenko H.O.', 'Vidsutnij');
insert into votes values(2763, 'Omel"yanovych D.S.', 'Za');
insert into votes values(2763, 'Orobec" L.Yu.', 'Za');
insert into votes values(2763, 'Pavlenko V.V.', 'Za');
insert into votes values(2763, 'Pavlenko S.H.', 'Za');
insert into votes values(2763, 'Palycya I.P.', 'Ne holosuvav');
insert into votes values(2763, 'Pashyns"kyj S.V.', 'Za');
insert into votes values(2763, 'Perestenko M.V.', 'Za');
insert into votes values(2763, 'Petruk M.M.', 'Za');
insert into votes values(2763, 'Pyeryedyerij V.H.', 'Za');
insert into votes values(2763, 'Pysarenko V.V.', 'Vidsutnij');
insert into votes values(2763, 'Pinchuk A.P.', 'Za');
insert into votes values(2763, 'Plotnikov O.V.', 'Za');
insert into votes values(2763, 'Plyushh I.S.', 'Za');
insert into votes values(2763, 'Polishhuk O.V.', 'Za');
insert into votes values(2763, 'Polunyeyev Yu.V.', 'Za');
insert into votes values(2763, 'Polyachenko V.A.', 'Za');
insert into votes values(2763, 'Potapov V.I.', 'Za');
insert into votes values(2763, 'Prasolov I.M.', 'Za');
insert into votes values(2763, 'Prytyka D.M.', 'Za');
insert into votes values(2763, 'Prutnik E.A.', 'Za');
insert into votes values(2763, 'Pshonka A.V.', 'Za');
insert into votes values(2763, 'Radovec" A.A.', 'Za');
insert into votes values(2763, 'Rybak V.V.', 'Za');
insert into votes values(2763, 'Romanyuk M.P.', 'Za');
insert into votes values(2763, 'Ryabeka O.H.', 'Za');
insert into votes values(2763, 'Savchuk O.V.', 'Za');
insert into votes values(2763, 'Samojlenko Yu.P.', 'Za');
insert into votes values(2763, 'Samofalov H.H.', 'Za');
insert into votes values(2763, 'Sas S.V.', 'Za');
insert into votes values(2763, 'Selivarov A.B.', 'Za');
insert into votes values(2763, 'Semynoha A.I.', 'Za');
insert into votes values(2763, 'Serbin Yu.S.', 'Za');
insert into votes values(2763, 'Synycya A.M.', 'Za');
insert into votes values(2763, 'Sidel"nyk I.I.', 'Za');
insert into votes values(2763, 'Skybinec"kyj O.M.', 'Za');
insert into votes values(2763, 'Skudar H.M.', 'Ne holosuvav');
insert into votes values(2763, 'Smityux H.Ye.', 'Za');
insert into votes values(2763, 'Sokolov M.V.', 'Za');
insert into votes values(2763, 'Sorochyns"ka-Kyrylenko R.M.', 'Za');
insert into votes values(2763, 'Stel"mashenko V.P.', 'Za');
insert into votes values(2763, 'Stec"kiv T.S.', 'Za');
insert into votes values(2763, 'Stojko I.M.', 'Za');
insert into votes values(2763, 'Stoyan O.M.', 'Za');
insert into votes values(2763, 'Sulkovs"kyj P.H.', 'Za');
insert into votes values(2763, 'Suslov Ye.I.', 'Za');
insert into votes values(2763, 'Sushkevych V.M.', 'Vidsutnij');
insert into votes values(2763, 'Taran V.V.', 'Za');
insert into votes values(2763, 'Tedeyev E.S.', 'Za');
insert into votes values(2763, 'Ter"oxin S.A.', 'Za');
insert into votes values(2763, 'Tkach R.V.', 'Za');
insert into votes values(2763, 'Tolstenko V.L.', 'Za');
insert into votes values(2763, 'Topolov V.S.', 'Za');
insert into votes values(2763, 'Trehubov Yu.V.', 'Za');
insert into votes values(2763, 'Tryndyuk Yu.H.', 'Za');
insert into votes values(2763, 'Turmanov V.I.', 'Za');
insert into votes values(2763, 'Unhuryan P.Ya.', 'Za');
insert into votes values(2763, 'Fedun O.L.', 'Za');
insert into votes values(2763, 'Fesenko L.I.', 'Za');
insert into votes values(2763, 'Fomin O.V.', 'Za');
insert into votes values(2763, 'Xarlim V.M.', 'Za');
insert into votes values(2763, 'Xmel"nyc"kyj V.I.', 'Za');
insert into votes values(2763, 'Xrapov S.A.', 'Za');
insert into votes values(2763, 'Car"ov O.A.', 'Za');
insert into votes values(2763, 'Cyurko P.I.', 'Za');
insert into votes values(2763, 'Chernomorov O.M.', 'Za');
insert into votes values(2763, 'Chertkov Yu.D.', 'Za');
insert into votes values(2763, 'Chornovil T.V.', 'Za');
insert into votes values(2763, 'Chudnov V.M.', 'Za');
insert into votes values(2763, 'Shaho Ye.P.', 'Za');
insert into votes values(2763, 'Sharov I.F.', 'Za');
insert into votes values(2763, 'Shevchenko A.V.', 'Za');
insert into votes values(2763, 'Shevchuk S.V.', 'Za');
insert into votes values(2763, 'Shencev D.O.', 'Za');
insert into votes values(2763, 'Shershun M.X.', 'Za');
insert into votes values(2763, 'Shyshkina Z.L.', 'Za');
insert into votes values(2763, 'Shkil" A.V.', 'Za');
insert into votes values(2763, 'Shkutyak Z.V.', 'Za');
insert into votes values(2763, 'Shmel"ova S.O.', 'Za');
insert into votes values(2763, 'Shpak V.F.', 'Za');
insert into votes values(2763, 'Shustik O.Yu.', 'Za');
insert into votes values(2763, 'Yushhenko P.A.', 'Za');
insert into votes values(2763, 'Yahoferov A.M.', 'Za');
insert into votes values(2763, 'Yanukovych V.V.', 'Za');
insert into votes values(2763, 'Yacenko A.V.', 'Vidsutnij');
insert into votes values(2763, 'Aleksandrovs"ka A.O.', 'Za');
insert into votes values(2763, 'Ar’yev V.I.', 'Za');
insert into votes values(2763, 'Arkallayev N.H.', 'Za');
insert into votes values(2763, 'Axmetov R.L.', 'Za');
insert into votes values(2763, 'Babenko V.B.', 'Za');
insert into votes values(2763, 'Bahrayev M.H.', 'Za');
insert into votes values(2763, 'Barvinenko V.D.', 'Za');
insert into votes values(2763, 'Bevz V.A.', 'Za');
insert into votes values(2763, 'Belousova I.A.', 'Za');
insert into votes values(2763, 'Bilyj O.P.', 'Za');
insert into votes values(2763, 'Bilorus O.H.', 'Za');
insert into votes values(2763, 'Bobyl"ov O.F.', 'Vidsutnij');
insert into votes values(2763, 'Bohoslovs"ka I.H.', 'Za');
insert into votes values(2763, 'Bodnar O.B.', 'Za');
insert into votes values(2763, 'Bolyura A.V.', 'Za');
insert into votes values(2763, 'Bondarenko V.V.', 'Za');
insert into votes values(2763, 'Bondarenko O.A.', 'Za');
insert into votes values(2763, 'Bondaryev K.A.', 'Za');
insert into votes values(2763, 'Borysov V.D.', 'Za');
insert into votes values(2763, 'Bort V.P.', 'Za');
insert into votes values(2763, 'Budzherak O.O.', 'Za');
insert into votes values(2763, 'But Yu.A.', 'Ne holosuvav');
insert into votes values(2763, 'Vasylenko S.V.', 'Za');
insert into votes values(2763, 'Vasyl"yev O.A.', 'Za');
insert into votes values(2763, 'Vashhuk K.T.', 'Ne holosuvala');
insert into votes values(2763, 'Verevs"kyj A.M.', 'Za');
insert into votes values(2763, 'Vetvyc"kyj D.O.', 'Za');
insert into votes values(2763, 'Vlasenko S.V.', 'Za');
insert into votes values(2763, 'Volynec" M.Ya.', 'Za');
insert into votes values(2763, 'Voropayev Yu.M.', 'Za');
insert into votes values(2763, 'V’yazivs"kyj V.M.', 'Za');
insert into votes values(2763, 'Hasyuk P.P.', 'Za');
insert into votes values(2763, 'Hejman O.A.', 'Za');
insert into votes values(2763, 'Herasym’yuk O.V.', 'Za');
insert into votes values(2763, 'Hyellyer Ye.B.', 'Za');
insert into votes values(2763, 'Hlus" S.K.', 'Za');
insert into votes values(2763, 'Hnatkevych Yu.V.', 'Za');
insert into votes values(2763, 'Holovchenko I.B.', 'Za');
insert into votes values(2763, 'Horbal" V.M.', 'Za');
insert into votes values(2763, 'Hordiyenko S.V.', 'Za');
insert into votes values(2763, 'Horoshkevych O.S.', 'Za');
insert into votes values(2763, 'Hryvkovs"kyj V.O.', 'Za');
insert into votes values(2763, 'Hrymchak Yu.M.', 'Vidsutnij');
insert into votes values(2763, 'Hryniv I.O.', 'Za');
insert into votes values(2763, 'Hrycenko A.S.', 'Za');
insert into votes values(2763, 'Hudyma O.M.', 'Za');
insert into votes values(2763, 'Humenyuk O.I.', 'Za');
insert into votes values(2763, 'Husarov S.M.', 'Za');
insert into votes values(2763, 'Davymuka S.A.', 'Za');
insert into votes values(2763, 'Danilov V.B.', 'Za');
insert into votes values(2763, 'Dejch B.D.', 'Za');
insert into votes values(2763, 'Demishkan V.F.', 'Za');
insert into votes values(2763, 'Demyanko M.I.', 'Za');
insert into votes values(2763, 'Den"kovych I.V.', 'Za');
insert into votes values(2763, 'Derkach A.L.', 'Za');
insert into votes values(2763, 'Dzhemilyev M. .', 'Za');
insert into votes values(2763, 'Dzhodzhyk Ya.I.', 'Za');
insert into votes values(2763, 'Dovhyj S.O.', 'Za');
insert into votes values(2763, 'Donchak V.A.', 'Za');
insert into votes values(2763, 'Dubovoj O.F.', 'Za');
insert into votes values(2763, 'Yehorov O.M.', 'Za');
insert into votes values(2763, 'Yeres"ko I.H.', 'Za');
insert into votes values(2763, 'Zhvaniya D.V.', 'Ne holosuvav');
insert into votes values(2763, 'Zhevaho K.V.', 'Za');
insert into votes values(2763, 'Zabars"kyj V.V.', 'Za');
insert into votes values(2763, 'Zabloc"kyj V.P.', 'Za');
insert into votes values(2763, 'Zayec" I.O.', 'Za');
insert into votes values(2763, 'Zasuxa T.V.', 'Za');
insert into votes values(2763, 'Zvarych R.M.', 'Za');
insert into votes values(2763, 'Zejnalov E.D.', 'Za');
insert into votes values(2763, 'Zlochevs"kyj M.V.', 'Za');
insert into votes values(2763, 'Zubanov V.O.', 'Za');
insert into votes values(2763, 'Zubyk V.V.', 'Za');
insert into votes values(2763, 'Ivanenko V.H.', 'Za');
insert into votes values(2763, 'Illyashov H.O.', 'Za');
insert into votes values(2763, 'Kaletnik H.M.', 'Za');
insert into votes values(2763, 'Kal"chenko V.M.', 'Za');
insert into votes values(2763, 'Kamchatnyj V.H.', 'Za');
insert into votes values(2763, 'Karakaj Yu.V.', 'Za');
insert into votes values(2763, 'Karpuk V.H.', 'Za');
insert into votes values(2763, 'Kasyanyuk O.R.', 'Za');
insert into votes values(2763, 'Kelestyn V.V.', 'Za');
insert into votes values(2763, 'Kendz"or Ya.M.', 'Za');
insert into votes values(2763, 'Kyrylenko V.A.', 'Za');
insert into votes values(2763, 'Kyryl"chuk Ye.I.', 'Za');
insert into votes values(2763, 'Kysel"ov V.O.', 'Za');
insert into votes values(2763, 'Kilinkarov S.P.', 'Za');
insert into votes values(2763, 'Klymenko O.I.', 'Za');
insert into votes values(2763, 'Klimov L.M.', 'Za');
insert into votes values(2763, 'Klyuchkovs"kyj Yu.B.', 'Ne holosuvav');
insert into votes values(2763, 'Kovalevs"ka Yu.S.', 'Za');
insert into votes values(2763, 'Koval"ova Yu.V.', 'Za');
insert into votes values(2763, 'Kozhara L.O.', 'Za');
insert into votes values(2763, 'Kozak V.V.', 'Za');
insert into votes values(2763, 'Kolesnichenko V.V.', 'Za');
insert into votes values(2763, 'Komar M.S.', 'Za');
insert into votes values(2763, 'Konovalyuk V.I.', 'Za');
insert into votes values(2763, 'Korzh V.P.', 'Za');
insert into votes values(2763, 'Korzh P.P.', 'Za');
insert into votes values(2763, 'Korolevs"ka N.Yu.', 'Za');
insert into votes values(2763, 'Kosiv M.V.', 'Za');
insert into votes values(2763, 'Kostenko Yu.I.', 'Za');
insert into votes values(2763, 'Kravchenko M.V.', 'Za');
insert into votes values(2763, 'Krajnij V.H.', 'Za');
insert into votes values(2763, 'Kruk Yu.B.', 'Za');
insert into votes values(2763, 'Kuz"menko P.P.', 'Za');
insert into votes values(2763, 'Kulykov K.B.', 'Za');
insert into votes values(2763, 'Kunchenko O.P.', 'Za');
insert into votes values(2763, 'Kurovs"kyj I.I.', 'Za');
insert into votes values(2763, 'Labuns"ka A.V.', 'Za');
insert into votes values(2763, 'Landik V.I.', 'Za');
insert into votes values(2763, 'Levcun V.I.', 'Za');
insert into votes values(2763, 'Lemza V.D.', 'Za');
insert into votes values(2763, 'Lysov I.V.', 'Za');
insert into votes values(2763, 'Lytvyn Yu.O.', 'Za');
insert into votes values(2763, 'Lychuk V.I.', 'Za');
insert into votes values(2763, 'Lohvynenko O.S.', 'Za');
insert into votes values(2763, 'Luk’yanov V.V.', 'Za');
insert into votes values(2763, 'Luk’yanchuk R.V.', 'Za');
insert into votes values(2763, 'L"ovochkina Yu.V.', 'Za');
insert into votes values(2763, 'Lyashko O.V.', 'Za');
insert into votes values(2763, 'Makeyenko V.V.', 'Za');
insert into votes values(2763, 'Malyshev V.S.', 'Za');
insert into votes values(2763, 'Mal"cev V.O.', 'Za');
insert into votes values(2763, 'Marmazov Ye.V.', 'Za');
insert into votes values(2763, 'Martynyuk A.I.', 'Za');
insert into votes values(2763, 'Matvyeyev V.H.', 'Za');
insert into votes values(2763, 'Matviyenko A.S.', 'Za');
insert into votes values(2763, 'Mel"nyk P.V.', 'Za');
insert into votes values(2763, 'Myrnyj I.M.', 'Za');
insert into votes values(2763, 'Miroshnychenko Yu.R.', 'Za');
insert into votes values(2763, 'Movchan P.M.', 'Za');
insert into votes values(2763, 'Momot S.V.', 'Ne holosuvav');
insert into votes values(2763, 'Moskal" H.H.', 'Za');
insert into votes values(2763, 'Moshak S.M.', 'Za');
insert into votes values(2763, 'Mxitaryan N.M.', 'Za');
insert into votes values(2763, 'Najd"onov A.M.', 'Za');
insert into votes values(2763, 'Novikov O.V.', 'Ne holosuvav');
insert into votes values(2763, 'Olijnyk V.S.', 'Za');
insert into votes values(2763, 'Olijnyk S.V.', 'Vidsutnij');
insert into votes values(2763, 'Omel"chenko O.O.', 'Vidsutnij');
insert into votes values(2763, 'Orlov A.V.', 'Za');
insert into votes values(2763, 'Osyka S.H.', 'Za');
insert into votes values(2763, 'Pavlenko E.I.', 'Za');
insert into votes values(2763, 'Pavlovs"kyj A.M.', 'Utrymavsya');
insert into votes values(2763, 'Parubij A.V.', 'Za');
insert into votes values(2763, 'Peklushenko O.M.', 'Za');
insert into votes values(2763, 'Petrenko V.M.', 'Za');
insert into votes values(2763, 'Pet"ovka V.V.', 'Za');
insert into votes values(2763, 'Pylypenko V.P.', 'Vidsutnij');
insert into votes values(2763, 'Pysarchuk P.I.', 'Za');
insert into votes values(2763, 'Piskun S.M.', 'Za');
insert into votes values(2763, 'Ploxoj I.I.', 'Za');
insert into votes values(2763, 'Podhornyj S.P.', 'Za');
insert into votes values(2763, 'Poloxalo V.I.', 'Za');
insert into votes values(2763, 'Polyanchych M.M.', 'Za');
insert into votes values(2763, 'Popesku I.V.', 'Za');
insert into votes values(2763, 'Potapchuk M.L.', 'Za');
insert into votes values(2763, 'Pryhods"kyj A.V.', 'Za');
insert into votes values(2763, 'Prokopchuk Yu.V.', 'Za');
insert into votes values(2763, 'Pudov B.M.', 'Za');
insert into votes values(2763, 'Radkovs"kyj O.V.', 'Za');
insert into votes values(2763, 'Reva D.O.', 'Za');
insert into votes values(2763, 'Rybakov I.O.', 'Za');
insert into votes values(2763, 'Rudchenko M.M.', 'Za');
insert into votes values(2763, 'Savchenko I.V.', 'Ne holosuvav');
insert into votes values(2763, 'Salamatin D.A.', 'Za');
insert into votes values(2763, 'Samojlyk K.S.', 'Za');
insert into votes values(2763, 'Sandler D.M.', 'Za');
insert into votes values(2763, 'Svyatash D.V.', 'Za');
insert into votes values(2763, 'Semerak O.M.', 'Za');
insert into votes values(2763, 'Senchenko A.V.', 'Za');
insert into votes values(2763, 'Symonenko P.M.', 'Za');
insert into votes values(2763, 'Sihal Ye.Ya.', 'Za');
insert into votes values(2763, 'Sinchenko V.M.', 'Za');
insert into votes values(2763, 'Skubenko V.P.', 'Vidsutnij');
insert into votes values(2763, 'Slobodyan O.V.', 'Za');
insert into votes values(2763, 'Sobolyev S.V.', 'Za');
insert into votes values(2763, 'Soloshenko M.P.', 'Za');
insert into votes values(2763, 'Sochka O.O.', 'Za');
insert into votes values(2763, 'Stec" Yu.Ya.', 'Za');
insert into votes values(2763, 'Steshenko O.M.', 'Za');
insert into votes values(2763, 'Stolar V.M.', 'Za');
insert into votes values(2763, 'Stretovych V.M.', 'Vidsutnij');
insert into votes values(2763, 'Suprunenko O.I.', 'Za');
insert into votes values(2763, 'Suxyj Ya.M.', 'Za');
insert into votes values(2763, 'Tabachnyk Ya.P.', 'Za');
insert into votes values(2763, 'Tarasyuk B.I.', 'Za');
insert into votes values(2763, 'Tereshhuk S.M.', 'Ne holosuvav');
insert into votes values(2763, 'Tyshhenko O.I.', 'Za');
insert into votes values(2763, 'Tkachenko O.M.', 'Za');
insert into votes values(2763, 'Tomenko M.V.', 'Za');
insert into votes values(2763, 'Trajduk M.F.', 'Za');
insert into votes values(2763, 'Tret"yakov O.Yu.', 'Za');
insert into votes values(2763, 'Trofymenko V.V.', 'Za');
insert into votes values(2763, 'Ukolov V.O.', 'Za');
insert into votes values(2763, 'Fedorchuk Ya.P.', 'Za');
insert into votes values(2763, 'Fel"dman O.B.', 'Za');
insert into votes values(2763, 'Filenko V.P.', 'Za');
insert into votes values(2763, 'Xara V.H.', 'Za');
insert into votes values(2763, 'Xarovs"kyj S.Yu.', 'Ne holosuvav');
insert into votes values(2763, 'Xomutynnik V.Yu.', 'Za');
insert into votes values(2763, 'Car"kov Ye.I.', 'Za');
insert into votes values(2763, 'Cybenko P.S.', 'Za');
insert into votes values(2763, 'Chepynoha V.M.', 'Za');
insert into votes values(2763, 'Cherpic"kyj O.Z.', 'Za');
insert into votes values(2763, 'Chechetov M.V.', 'Za');
insert into votes values(2763, 'Chornovolenko O.V.', 'Za');
insert into votes values(2763, 'Chudnovs"kyj V.O.', 'Za');
insert into votes values(2763, 'Shamanov V.V.', 'Za');
insert into votes values(2763, 'Shvec" V.D.', 'Za');
insert into votes values(2763, 'Shevchuk O.B.', 'Za');
insert into votes values(2763, 'Shemchuk V.V.', 'Vidsutnij');
insert into votes values(2763, 'Shepelev O.O.', 'Za');
insert into votes values(2763, 'Shyshkina E.V.', 'Za');
insert into votes values(2763, 'Shyyanov B.A.', 'Za');
insert into votes values(2763, 'Shkirya I.M.', 'Za');
insert into votes values(2763, 'Shlemko D.V.', 'Za');
insert into votes values(2763, 'Shmidt M.O.', 'Za');
insert into votes values(2763, 'Shpenov D.Yu.', 'Za');
insert into votes values(2763, 'Shherban" A.V.', 'Za');
insert into votes values(2763, 'Yavorivs"kyj V.O.', 'Za');
insert into votes values(2763, 'Yankovs"kyj M.A.', 'Za');
insert into votes values(2763, 'Yaroshhuk V.I.', 'Za');
insert into votes values(2763, 'Yacenyuk A.P.', 'Za');
insert into votes values(10155, 'Abdullin O.R.', 'Vidsutnij');
insert into votes values(10155, 'Aleksyeyev I.V.', 'Ne holosuvav');
insert into votes values(10155, 'Ar’yev V.I.', 'Vidsutnij');
insert into votes values(10155, 'Arkallayev N.H.', 'Za');
insert into votes values(10155, 'Axmetov R.L.', 'Za');
insert into votes values(10155, 'Baburin O.V.', 'Ne holosuvav');
insert into votes values(10155, 'Baranov V.O.', 'Za');
insert into votes values(10155, 'Barvinenko V.D.', 'Za');
insert into votes values(10155, 'Bevz V.A.', 'Ne holosuvav');
insert into votes values(10155, 'Belousova I.A.', 'Za');
insert into votes values(10155, 'Berezkin S.S.', 'Za');
insert into votes values(10155, 'Bilyj O.P.', 'Za');
insert into votes values(10155, 'Bilorus O.H.', 'Vidsutnij');
insert into votes values(10155, 'Bobyl"ov O.F.', 'Za');
insert into votes values(10155, 'Bohoslovs"ka I.H.', 'Za');
insert into votes values(10155, 'Bodnar O.B.', 'Vidsutnya');
insert into votes values(10155, 'Bolyura A.V.', 'Vidsutnya');
insert into votes values(10155, 'Bondarenko V.V.', 'Za');
insert into votes values(10155, 'Bondarenko O.A.', 'Za');
insert into votes values(10155, 'Bondaryev K.A.', 'Vidsutnij');
insert into votes values(10155, 'Borysov V.D.', 'Za');
insert into votes values(10155, 'Bort V.P.', 'Za');
insert into votes values(10155, 'Buryak O.V.', 'Za');
insert into votes values(10155, 'Vasadze T.Sh.', 'Za');
insert into votes values(10155, 'Vasyl"yev H.A.', 'Za');
insert into votes values(10155, 'Vasyutin S.I.', 'Za');
insert into votes values(10155, 'Velizhans"kyj S.K.', 'Vidsutnij');
insert into votes values(10155, 'Vernydubov I.V.', 'Za');
insert into votes values(10155, 'Vecherko V.M.', 'Za');
insert into votes values(10155, 'Volynec" Ye.V.', 'Ne holosuvav');
insert into votes values(10155, 'Volkov O.A.', 'Za');
insert into votes values(10155, 'Vorotnyuk I.B.', 'Za');
insert into votes values(10155, 'Hajdayev Yu.O.', 'Ne holosuvav');
insert into votes values(10155, 'Hasyuk P.P.', 'Za');
insert into votes values(10155, 'Hejman O.A.', 'Za');
insert into votes values(10155, 'Herasym’yuk O.V.', 'Vidsutnya');
insert into votes values(10155, 'Hyellyer Ye.B.', 'Za');
insert into votes values(10155, 'Hlus" S.K.', 'Za');
insert into votes values(10155, 'Hnatkevych Yu.V.', 'Vidsutnij');
insert into votes values(10155, 'Holub O.V.', 'Ne holosuvav');
insert into votes values(10155, 'Horbatyuk A.O.', 'Za');
insert into votes values(10155, 'Horina I.A.', 'Za');
insert into votes values(10155, 'Hrach L.I.', 'Vidsutnij');
insert into votes values(10155, 'Hryhorovych L.S.', 'Vidsutnya');
insert into votes values(10155, 'Hrynevec"kyj S.R.', 'Za');
insert into votes values(10155, 'Hrycak V.M.', 'Za');
insert into votes values(10155, 'Hubs"kyj B.V.', 'Za');
insert into votes values(10155, 'Humenyuk I.M.', 'Za');
insert into votes values(10155, 'Hureyev V.M.', 'Za');
insert into votes values(10155, 'Davydenko A.A.', 'Vidsutnij');
insert into votes values(10155, 'Danylenko V.A.', 'Ne holosuvav');
insert into votes values(10155, 'Darda O.P.', 'Za');
insert into votes values(10155, 'Demydko V.M.', 'Za');
insert into votes values(10155, 'Demyanko M.I.', 'Za');
insert into votes values(10155, 'Den"kovych I.V.', 'Za');
insert into votes values(10155, 'Derkach A.L.', 'Za');
insert into votes values(10155, 'Dzhemilyev M. .', 'Vidsutnij');
insert into votes values(10155, 'Dobryak Ye.D.', 'Vidsutnij');
insert into votes values(10155, 'Donij O.S.', 'Vidsutnij');
insert into votes values(10155, 'Dubil" V.O.', 'Vidsutnij');
insert into votes values(10155, 'Yevtuxov V.I.', 'Za');
insert into votes values(10155, 'Yehorov O.M.', 'Za');
insert into votes values(10155, 'Yeres"ko I.H.', 'Vidsutnij');
insert into votes values(10155, 'Zhvaniya D.V.', 'Vidsutnij');
insert into votes values(10155, 'Zhevaho K.V.', 'Vidsutnij');
insert into votes values(10155, 'Zhuravs"kyj V.S.', 'Za');
insert into votes values(10155, 'Zabzalyuk R.O.', 'Vidsutnij');
insert into votes values(10155, 'Zadyrko H.O.', 'Za');
insert into votes values(10155, 'Zarubins"kyj O.O.', 'Za');
insert into votes values(10155, 'Zac O.V.', 'Za');
insert into votes values(10155, 'Zvarych R.M.', 'Vidsutnij');
insert into votes values(10155, 'Zejnalov E.D.', 'Vidsutnij');
insert into votes values(10155, 'Zozulya R.P.', 'Vidsutnij');
insert into votes values(10155, 'Zubec" M.V.', 'Za');
insert into votes values(10155, 'Zubov V.S.', 'Za');
insert into votes values(10155, 'Ivanyushhenko Yu.V.', 'Za');
insert into votes values(10155, 'Kaletnik H.M.', 'Za');
insert into votes values(10155, 'Kalyuzhnyj V.A.', 'Za');
insert into votes values(10155, 'Kapliyenko V.V.', 'Za');
insert into votes values(10155, 'Karmazin Yu.A.', 'Vidsutnij');
insert into votes values(10155, 'Kasyanyuk O.R.', 'Za');
insert into votes values(10155, 'Kelestyn V.V.', 'Za');
insert into votes values(10155, 'Kendz"or Ya.M.', 'Vidsutnij');
insert into votes values(10155, 'Kyrylenko V.A.', 'Vidsutnij');
insert into votes values(10155, 'Kyryl"chuk Ye.I.', 'Vidsutnij');
insert into votes values(10155, 'Kysel"ov V.O.', 'Za');
insert into votes values(10155, 'Kilinkarov S.P.', 'Ne holosuvav');
insert into votes values(10155, 'Klymenko O.I.', 'Vidsutnij');
insert into votes values(10155, 'Klimov L.M.', 'Za');
insert into votes values(10155, 'Klyuchkovs"kyj Yu.B.', 'Vidsutnij');
insert into votes values(10155, 'Kovalevs"ka Yu.S.', 'Za');
insert into votes values(10155, 'Koval"ova Yu.V.', 'Za');
insert into votes values(10155, 'Kozhara L.O.', 'Za');
insert into votes values(10155, 'Kozub O.A.', 'Za');
insert into votes values(10155, 'Kolocej Yu.O.', 'Za');
insert into votes values(10155, 'Kondratyuk O.K.', 'Vidsutnya');
insert into votes values(10155, 'Konstantynov Ye.S.', 'Za');
insert into votes values(10155, 'Korzh V.T.', 'Vidsutnij');
insert into votes values(10155, 'Korzhev A.L.', 'Za');
insert into votes values(10155, 'Korotyuk V.I.', 'Vidsutnij');
insert into votes values(10155, 'Kostenko P.I.', 'Vidsutnij');
insert into votes values(10155, 'Koshyn S.M.', 'Vidsutnij');
insert into votes values(10155, 'Kravchuk V.P.', 'Vidsutnij');
insert into votes values(10155, 'Kril" I.I.', 'Vidsutnij');
insert into votes values(10155, 'Kruc" M.F.', 'Vidsutnij');
insert into votes values(10155, 'Kuz"muk O.I.', 'Za');
insert into votes values(10155, 'Kul"chyns"kyj M.H.', 'Vidsutnij');
insert into votes values(10155, 'Kurylo V.S.', 'Za');
insert into votes values(10155, 'Kurpil" S.V.', 'Vidsutnij');
insert into votes values(10155, 'Landyk V.I.', 'Za');
insert into votes values(10155, 'Lanovyj V.T.', 'Vidsutnij');
insert into votes values(10155, 'Levcun V.I.', 'Vidsutnij');
insert into votes values(10155, 'Leshhenko V.O.', 'Ne holosuvav');
insert into votes values(10155, 'Lysov I.V.', 'Za');
insert into votes values(10155, 'Lytvyn Yu.O.', 'Za');
insert into votes values(10155, 'Lychuk V.I.', 'Za');
insert into votes values(10155, 'Lohvynenko O.S.', 'Vidsutnij');
insert into votes values(10155, 'Luk’yanov V.V.', 'Za');
insert into votes values(10155, 'Luk’yanchuk R.V.', 'Vidsutnij');
insert into votes values(10155, 'L"ovochkina Yu.V.', 'Za');
insert into votes values(10155, 'Lyashko O.V.', 'Vidsutnij');
insert into votes values(10155, 'Makeyenko V.V.', 'Za');
insert into votes values(10155, 'Malyshev V.S.', 'Za');
insert into votes values(10155, 'Mal"cev V.O.', 'Za');
insert into votes values(10155, 'Marmazov Ye.V.', 'Ne holosuvav');
insert into votes values(10155, 'Martynyuk A.I.', 'Ne holosuvav');
insert into votes values(10155, 'Matvyeyev V.H.', 'Ne holosuvav');
insert into votes values(10155, 'Matviyenko A.S.', 'Vidsutnij');
insert into votes values(10155, 'Mel"nyk S.A.', 'Za');
insert into votes values(10155, 'Myronenko M.I.', 'Za');
insert into votes values(10155, 'Mishhenko S.H.', 'Vidsutnij');
insert into votes values(10155, 'Mojsyk V.R.', 'Vidsutnij');
insert into votes values(10155, 'Moroko Yu.M.', 'Za');
insert into votes values(10155, 'Mostipan U.M.', 'Vidsutnya');
insert into votes values(10155, 'Muc O.P.', 'Za');
insert into votes values(10155, 'Nadosha O.V.', 'Za');
insert into votes values(10155, 'Nakonechnyj V.L.', 'Za');
insert into votes values(10155, 'Novikov O.V.', 'Vidsutnij');
insert into votes values(10155, 'Olijnyk V.S.', 'Vidsutnij');
insert into votes values(10155, 'Olijnyk S.V.', 'Vidsutnij');
insert into votes values(10155, 'Omel"chenko O.O.', 'Za');
insert into votes values(10155, 'Orlov A.V.', 'Za');
insert into votes values(10155, 'Osyka S.H.', 'Za');
insert into votes values(10155, 'Pavlenko E.I.', 'Za');
insert into votes values(10155, 'Pavlovs"kyj A.M.', 'Vidsutnij');
insert into votes values(10155, 'Parubij A.V.', 'Vidsutnij');
insert into votes values(10155, 'Pashyns"kyj S.V.', 'Vidsutnij');
insert into votes values(10155, 'Petrenko V.M.', 'Vidsutnij');
insert into votes values(10155, 'Pet"ovka V.V.', 'Vidsutnij');
insert into votes values(10155, 'Pylypenko V.P.', 'Vidsutnij');
insert into votes values(10155, 'Pysarchuk P.I.', 'Za');
insert into votes values(10155, 'Piskun S.M.', 'Za');
insert into votes values(10155, 'Ploxoj I.I.', 'Ne holosuvav');
insert into votes values(10155, 'Podhornyj S.P.', 'Vidsutnij');
insert into votes values(10155, 'Polyanchych M.M.', 'Vidsutnij');
insert into votes values(10155, 'Potapov V.I.', 'Za');
insert into votes values(10155, 'Prasolov I.M.', 'Za');
insert into votes values(10155, 'Prytyka D.M.', 'Za');
insert into votes values(10155, 'Prutnik E.A.', 'Za');
insert into votes values(10155, 'Pshonka A.V.', 'Za');
insert into votes values(10155, 'Radovec" A.A.', 'Za');
insert into votes values(10155, 'Remez V.V.', 'Za');
insert into votes values(10155, 'Rybakov I.O.', 'Za');
insert into votes values(10155, 'Rudchenko M.M.', 'Za');
insert into votes values(10155, 'Savchenko I.V.', 'Za');
insert into votes values(10155, 'Samojlenko Yu.P.', 'Za');
insert into votes values(10155, 'Samofalov H.H.', 'Za');
insert into votes values(10155, 'Sas S.V.', 'Vidsutnij');
insert into votes values(10155, 'Selivarov A.B.', 'Za');
insert into votes values(10155, 'Semynoha A.I.', 'Vidsutnij');
insert into votes values(10155, 'Serbin Yu.S.', 'Vidsutnij');
insert into votes values(10155, 'Synycya A.M.', 'Za');
insert into votes values(10155, 'Sidel"nyk I.I.', 'Za');
insert into votes values(10155, 'Skybinec"kyj O.M.', 'Vidsutnij');
insert into votes values(10155, 'Skudar H.M.', 'Za');
insert into votes values(10155, 'Smityux H.Ye.', 'Za');
insert into votes values(10155, 'Sokolov M.V.', 'Vidsutnij');
insert into votes values(10155, 'Soltus P.S.', 'Za');
insert into votes values(10155, 'Sochka O.O.', 'Vidsutnij');
insert into votes values(10155, 'Stepanenko A.A.', 'Za');
insert into votes values(10155, 'Stec"kiv T.S.', 'Vidsutnij');
insert into votes values(10155, 'Stojko I.M.', 'Vidsutnij');
insert into votes values(10155, 'Stoyan O.M.', 'Za');
insert into votes values(10155, 'Sulkovs"kyj P.H.', 'Za');
insert into votes values(10155, 'Suslov Ye.I.', 'Vidsutnij');
insert into votes values(10155, 'Sushkevych V.M.', 'Vidsutnij');
insert into votes values(10155, 'Talyshev Ye.I.', 'Vidsutnij');
insert into votes values(10155, 'Tarasyuk B.I.', 'Vidsutnij');
insert into votes values(10155, 'Tereshhuk S.M.', 'Za');
insert into votes values(10155, 'Tyshhenko O.I.', 'Vidsutnij');
insert into votes values(10155, 'Tkachenko O.M.', 'Ne holosuvav');
insert into votes values(10155, 'Tomenko M.V.', 'Vidsutnij');
insert into votes values(10155, 'Trajduk M.F.', 'Za');
insert into votes values(10155, 'Tret"yakov O.Yu.', 'Vidsutnij');
insert into votes values(10155, 'Trofymenko V.V.', 'Vidsutnij');
insert into votes values(10155, 'Ukolov V.O.', 'Vidsutnij');
insert into votes values(10155, 'Fedorchuk Ya.P.', 'Vidsutnij');
insert into votes values(10155, 'Fel"dman O.B.', 'Za');
insert into votes values(10155, 'Fomin O.V.', 'Vidsutnij');
insert into votes values(10155, 'Xarlim V.M.', 'Za');
insert into votes values(10155, 'Xmel"nyc"kyj V.I.', 'Za');
insert into votes values(10155, 'Xrapov S.A.', 'Ne holosuvav');
insert into votes values(10155, 'Car"ov O.A.', 'Za');
insert into votes values(10155, 'Cyurko P.I.', 'Za');
insert into votes values(10155, 'Chernij V.V.', 'Za');
insert into votes values(10155, 'Cherpic"kyj O.Z.', 'Za');
insert into votes values(10155, 'Chechetov M.V.', 'Za');
insert into votes values(10155, 'Chornovolenko O.V.', 'Vidsutnij');
insert into votes values(10155, 'Chudnovs"kyj V.O.', 'Vidsutnij');
insert into votes values(10155, 'Shamanov V.V.', 'Za');
insert into votes values(10155, 'Shvec" V.D.', 'Vidsutnij');
insert into votes values(10155, 'Shevchuk O.B.', 'Vidsutnij');
insert into votes values(10155, 'Shemchuk V.V.', 'Vidsutnij');
insert into votes values(10155, 'Shepelev O.O.', 'Za');
insert into votes values(10155, 'Shyshkina E.V.', 'Vidsutnya');
insert into votes values(10155, 'Shyyanov B.A.', 'Vidsutnij');
insert into votes values(10155, 'Shkirya I.M.', 'Za');
insert into votes values(10155, 'Shlemko D.V.', 'Vidsutnij');
insert into votes values(10155, 'Shmidt M.O.', 'Za');
insert into votes values(10155, 'Shpenov D.Yu.', 'Za');
insert into votes values(10155, 'Shherban" A.V.', 'Ne holosuvav');
insert into votes values(10155, 'Yavorivs"kyj V.O.', 'Vidsutnij');
insert into votes values(10155, 'Yankovs"kyj M.A.', 'Za');
insert into votes values(10155, 'Yaroshhuk V.I.', 'Za');
insert into votes values(10155, 'Yacenyuk A.P.', 'Vidsutnij');
insert into votes values(10155, 'Aleksandrovs"ka A.O.', 'Ne holosuvala');
insert into votes values(10155, 'Andros S.O.', 'Za');
insert into votes values(10155, 'Arzhevitin S.M.', 'Vidsutnij');
insert into votes values(10155, 'Arutyunov H.R.', 'Vidsutnij');
insert into votes values(10155, 'Babenko V.B.', 'Vidsutnij');
insert into votes values(10155, 'Bahrayev M.H.', 'Za');
insert into votes values(10155, 'Baranov-Moxort S.M.', 'Za');
insert into votes values(10155, 'Baxteyeva T.D.', 'Za');
insert into votes values(10155, 'Bevzenko V.F.', 'Za');
insert into votes values(10155, 'Berezhna I.H.', 'Za');
insert into votes values(10155, 'Bilash B.F.', 'Za');
insert into votes values(10155, 'Bilozir O.V.', 'Vidsutnya');
insert into votes values(10155, 'Biryuk L.V.', 'Vidsutnij');
insert into votes values(10155, 'Bohdan R.D.', 'Vidsutnij');
insert into votes values(10155, 'Bohuslayev V.O.', 'Za');
insert into votes values(10155, 'Boldyryev Yu.O.', 'Za');
insert into votes values(10155, 'Bondar O.M.', 'Vidsutnij');
insert into votes values(10155, 'Bondarenko V.D.', 'Vidsutnij');
insert into votes values(10155, 'Bondarenko O.F.', 'Vidsutnya');
insert into votes values(10155, 'Bondyk V.A.', 'Za');
insert into votes values(10155, 'Borodin V.V.', 'Vidsutnij');
insert into votes values(10155, 'Budzherak O.O.', 'Za');
insert into votes values(10155, 'But Yu.A.', 'Za');
insert into votes values(10155, 'Vasylenko S.V.', 'Za');
insert into votes values(10155, 'Vasyl"yev O.A.', 'Za');
insert into votes values(10155, 'Vashhuk K.T.', 'Za');
insert into votes values(10155, 'Verevs"kyj A.M.', 'Za');
insert into votes values(10155, 'Vetvyc"kyj D.O.', 'Vidsutnij');
insert into votes values(10155, 'Vlasenko S.V.', 'Vidsutnij');
insert into votes values(10155, 'Volynec" M.Ya.', 'Vidsutnij');
insert into votes values(10155, 'Voropayev Yu.M.', 'Za');
insert into votes values(10155, 'V’yazivs"kyj V.M.', 'Vidsutnij');
insert into votes values(10155, 'Hanushhak Yu.I.', 'Vidsutnij');
insert into votes values(10155, 'Hac"ko V.P.', 'Za');
insert into votes values(10155, 'Herasymchuk V.V.', 'Za');
insert into votes values(10155, 'Herashhenko I.V.', 'Vidsutnya');
insert into votes values(10155, 'Hlazunov S.M.', 'Za');
insert into votes values(10155, 'Hlushhenko I.M.', 'Za');
insert into votes values(10155, 'Holovatyj S.P.', 'Vidsutnij');
insert into votes values(10155, 'Horbal" V.M.', 'Za');
insert into votes values(10155, 'Hordiyenko S.V.', 'Ne holosuvav');
insert into votes values(10155, 'Horoshkevych O.S.', 'Za');
insert into votes values(10155, 'Hryvkovs"kyj V.O.', 'Za');
insert into votes values(10155, 'Hrymchak Yu.M.', 'Vidsutnij');
insert into votes values(10155, 'Hryniv I.O.', 'Vidsutnij');
insert into votes values(10155, 'Hrycenko A.S.', 'Vidsutnij');
insert into votes values(10155, 'Hudyma O.M.', 'Vidsutnij');
insert into votes values(10155, 'Humenyuk O.I.', 'Vidsutnij');
insert into votes values(10155, 'Husarov S.M.', 'Za');
insert into votes values(10155, 'Davymuka S.A.', 'Vidsutnij');
insert into votes values(10155, 'Danilov V.B.', 'Vidsutnij');
insert into votes values(10155, 'Dejch B.D.', 'Za');
insert into votes values(10155, 'Demchyshen V.V.', 'Za');
insert into votes values(10155, 'Dem’yanchuk V.O.', 'Ne holosuvala');
insert into votes values(10155, 'Derevlyanyj V.T.', 'Vidsutnij');
insert into votes values(10155, 'Derkach M.I.', 'Za');
insert into votes values(10155, 'Dzhodzhyk Ya.I.', 'Vidsutnij');
insert into votes values(10155, 'Dovhyj S.O.', 'Za');
insert into votes values(10155, 'Donchak V.A.', 'Vidsutnij');
insert into votes values(10155, 'Dubovoj O.F.', 'Vidsutnij');
insert into votes values(10155, 'Yehorenko T.V.', 'Za');
insert into votes values(10155, 'Yedin O.J.', 'Za');
insert into votes values(10155, 'Yefremov O.S.', 'Za');
insert into votes values(10155, 'Zhebrivs"kyj P.I.', 'Vidsutnij');
insert into votes values(10155, 'Zhuravko O.V.', 'Za');
insert into votes values(10155, 'Zabars"kyj V.V.', 'Za');
insert into votes values(10155, 'Zabloc"kyj V.P.', 'Za');
insert into votes values(10155, 'Zayec" I.O.', 'Vidsutnij');
insert into votes values(10155, 'Zasuxa T.V.', 'Za');
insert into votes values(10155, 'Zvarych I.T.', 'Za');
insert into votes values(10155, 'Zvyahil"s"kyj Yu.L.', 'Za');
insert into votes values(10155, 'Zimin Ye.I.', 'Vidsutnij');
insert into votes values(10155, 'Zubanov V.O.', 'Za');
insert into votes values(10155, 'Zubyk V.V.', 'Za');
insert into votes values(10155, 'Ivanenko V.H.', 'Za');
insert into votes values(10155, 'Isayev L.O.', 'Za');
insert into votes values(10155, 'Kal"chenko V.M.', 'Vidsutnij');
insert into votes values(10155, 'Kamchatnyj V.H.', 'Za');
insert into votes values(10155, 'Karakaj Yu.V.', 'Za');
insert into votes values(10155, 'Karpuk V.H.', 'Vidsutnij');
insert into votes values(10155, 'Katerynchuk M.D.', 'Vidsutnij');
insert into votes values(10155, 'Kemenyash O.M.', 'Vidsutnij');
insert into votes values(10155, 'Kyj S.V.', 'Za');
insert into votes values(10155, 'Kyrylenko I.H.', 'Vidsutnij');
insert into votes values(10155, 'Kyrychok O.E.', 'Za');
insert into votes values(10155, 'Kivalov S.V.', 'Za');
insert into votes values(10155, 'Kinax A.K.', 'Za');
insert into votes values(10155, 'Klymec" P.A.', 'Za');
insert into votes values(10155, 'Klyuyev S.P.', 'Za');
insert into votes values(10155, 'Knyazevych R.P.', 'Vidsutnij');
insert into votes values(10155, 'Koval" V.S.', 'Vidsutnij');
insert into votes values(10155, 'Kovzel" M.O.', 'Vidsutnij');
insert into votes values(10155, 'Kozhem’yakin A.A.', 'Vidsutnij');
insert into votes values(10155, 'Kolesnichenko V.V.', 'Za');
insert into votes values(10155, 'Komar M.S.', 'Za');
insert into votes values(10155, 'Konovalyuk V.I.', 'Za');
insert into votes values(10155, 'Korzh V.P.', 'Za');
insert into votes values(10155, 'Korzh P.P.', 'Za');
insert into votes values(10155, 'Korolevs"ka N.Yu.', 'Vidsutnya');
insert into votes values(10155, 'Kosiv M.V.', 'Vidsutnij');
insert into votes values(10155, 'Kostenko Yu.I.', 'Vidsutnij');
insert into votes values(10155, 'Kravchenko M.V.', 'Ne holosuvav');
insert into votes values(10155, 'Krajnij V.H.', 'Vidsutnij');
insert into votes values(10155, 'Kruk Yu.B.', 'Za');
insert into votes values(10155, 'Kuz"menko P.P.', 'Za');
insert into votes values(10155, 'Kulykov K.B.', 'Vidsutnij');
insert into votes values(10155, 'Kunchenko O.P.', 'Za');
insert into votes values(10155, 'Kurovs"kyj I.I.', 'Vidsutnij');
insert into votes values(10155, 'Labuns"ka A.V.', 'Vidsutnya');
insert into votes values(10155, 'Landik V.I.', 'Za');
insert into votes values(10155, 'Lebedyev P.V.', 'Za');
insert into votes values(10155, 'Lemza V.D.', 'Vidsutnij');
insert into votes values(10155, 'Lyeshhyns"kyj O.O.', 'Za');
insert into votes values(10155, 'Lytvyn V.M.', 'Vidsutnij');
insert into votes values(10155, 'Lytvynov L.F.', 'Za');
insert into votes values(10155, 'Litvinov V.H.', 'Za');
insert into votes values(10155, 'Lukashuk O.H.', 'Vidsutnij');
insert into votes values(10155, 'Luk’yanova K.Ye.', 'Vidsutnya');
insert into votes values(10155, 'Luc"kyj M.H.', 'Za');
insert into votes values(10155, 'Lyapina K.M.', 'Vidsutnya');
insert into votes values(10155, 'Majboroda S.F.', 'Za');
insert into votes values(10155, 'Makiyenko V.P.', 'Vidsutnij');
insert into votes values(10155, 'Malich O.V.', 'Za');
insert into votes values(10155, 'Man"kovs"kyj H.V.', 'Za');
insert into votes values(10155, 'Martynenko M.V.', 'Vidsutnij');
insert into votes values(10155, 'Marushhenko V.S.', 'Vidsutnij');
insert into votes values(10155, 'Matvyeyev V.J.', 'Ne holosuvav');
insert into votes values(10155, 'Mel"nyk P.V.', 'Za');
insert into votes values(10155, 'Myrnyj I.M.', 'Za');
insert into votes values(10155, 'Miroshnychenko Yu.R.', 'Za');
insert into votes values(10155, 'Movchan P.M.', 'Za');
insert into votes values(10155, 'Momot S.V.', 'Za');
insert into votes values(10155, 'Moskal" H.H.', 'Vidsutnij');
insert into votes values(10155, 'Moshak S.M.', 'Za');
insert into votes values(10155, 'Mxitaryan N.M.', 'Za');
insert into votes values(10155, 'Najd"onov A.M.', 'Ne holosuvav');
insert into votes values(10155, 'Netec"ka O.A.', 'Za');
insert into votes values(10155, 'Odarchenko Yu.V.', 'Vidsutnij');
insert into votes values(10155, 'Olijnyk V.M.', 'Za');
insert into votes values(10155, 'Omel"chenko H.O.', 'Vidsutnij');
insert into votes values(10155, 'Omel"yanovych D.S.', 'Za');
insert into votes values(10155, 'Orobec" L.Yu.', 'Vidsutnya');
insert into votes values(10155, 'Pavlenko V.V.', 'Za');
insert into votes values(10155, 'Pavlenko S.H.', 'Za');
insert into votes values(10155, 'Palycya I.P.', 'Vidsutnij');
insert into votes values(10155, 'Pachesyuk S.N.', 'Za');
insert into votes values(10155, 'Perestenko M.V.', 'Ne holosuvala');
insert into votes values(10155, 'Petruk M.M.', 'Vidsutnij');
insert into votes values(10155, 'Pyeryedyerij V.H.', 'Vidsutnij');
insert into votes values(10155, 'Pysarenko V.V.', 'Za');
insert into votes values(10155, 'Pinchuk A.P.', 'Za');
insert into votes values(10155, 'Plotnikov O.V.', 'Za');
insert into votes values(10155, 'Plyushh I.S.', 'Za');
insert into votes values(10155, 'Polunyeyev Yu.V.', 'Za');
insert into votes values(10155, 'Popesku I.V.', 'Za');





commit;


